### ISSUE TITLE
AdminAuth using token fails

### ISSUE THREAD

**Issue by crackytsi** [node-red/node-red#2642] opened 2020-07-06 09:19 UTC
### What are the steps to reproduce?
Configure header based authentication for Node-Red.
Use the following modification of settings.js for NodeRed, where example@example.com represents the token:
```
    adminAuth: {
    tokens: function(token) {
        return new Promise(function(resolve, reject) {
            if ("example@example.com" == token) {
                // Resolve with the user object. It must contain
                // properties 'username' and 'permissions'
                var user = { username: 'admin', permissions: '*' };
                resolve(user);
            } else {
                // Resolve with null as this user does not exist
                resolve(null);
            }
        });
    },
},
```

### What happens?
Authentication failes, we just see a screen showing login dialog (without any input field).
See also https://discourse.nodered.org/t/issues-using-new-token-attribute-in-adminauth/29588

### What do you expect to happen?
User should be authenticated

### Please tell us about your environment:

- [x] Node-RED version: 1.1.0
- [x] Node.js version: v12.18.0
- [x] npm version: 6.14.4
- [x] Platform/OS: debian latest
- [x] Browser: chrome

**Comment by knolleary** [comment] 2020-07-06 09:21
The authentication of the WebSocket comms link between the editor and the runtime doesn't take into account the new tokens option - it only validates against the built-in token store.

The fix is for the comms authentication code to use the new tokens option if present.

**Comment by knolleary** [comment] 2020-07-09 11:28
Whilst the fix released in 1.1.1 is good, it still requires the editor to be given the token (via the `access_token` query param) so it can be passed over the WebSocket link.

In the case of a reverse proxy being used to add a custom header to the requests, the editor never sees the token, so the WebSocket auth fails.

Need to look more at how the WebSocket is authenticated and whether it'll be possible to handle this scenario.

**Closed** 2020-07-09 18:08 UTC
Labels: bug

**Comment by xsShuang** [comment] 2024-05-16 15:44
I also encountered this issue in the latest version. How can I solve it

Please tell us about your environment:
 Node-RED version: 3.1.9
 Node.js version: v16.20.1
 npm version: 8.19.4
 Platform/OS: win11
 Browser: edge

**Comment by hardillb** [comment] 2024-05-16 15:52
@xsShuang 

This issue has been closed for over 4 years.

Please ask questions on the Discourse forum first and include more information e.g. details of how you have configured Node-RED and details of if this was working before and if so what you changed

**Comment by xsShuang** [comment] 2024-05-20 01:59
I have already asked a question on the forum, but I have not received any useful response. Here is the address where I asked the question: https://discourse.nodered.org/t/custom-authentication-tokens-in-the-case-of-source-compilation-following-the-official-example-does-not-work/88025

**Custom authentication tokens, In the case of source compilation, following the official example does not work**

I want to secure Node-RED using a token. I am embedding Node-RED within my website, and I want access to Node-RED to be restricted only through the website. An example of this is provided below:

```
 adminAuth: {
        tokens: function(token) {
            return new Promise(function(resolve, reject) {
                // Check if the token is valid
                if (token === 'rdp2vex0nq4mzl8tf8hba1tpr5umtmzn') {
                    // Resolve with the user object
                    var user = { username: 'admin', permissions: '*' };
                    resolve(user);
                } else {
                    // Resolve with null if the token is not valid
                    resolve(null);
                }
            });
        },
    
    },
```
I've managed to secure access to Node-RED. However, I feel like it's not the right way, but it works.
the problem is there is no protection on Nodes itself, for example, the Node-RED dashboard.
I've seen this concept implemented in home assistant, but I don't understand how

**Comment by hardillb** [comment] 2024-05-20 06:59
As pointed out in the first answer on the forum, the Node-RED Editor is secured separately from things like the http-in/http-out and Node-RED Dashboard.

This means that any tokens configured using the `adminAuth` settings will NOT apply to the Node-RED Dashboard.

To secure things like the dashboard you need to make use of the `httpNodeAuth` or write your own custom middleware using the `httpNodeMiddleware`, both of these are described in the docs `[here](https://nodered.org/docs/user-guide/runtime/securing-node-red#http-node-security)`

As you have said that you have got the `adminAuth` tokens to work, please continue to engage on the forums for questions about `httpNodeAuth` or `httpNodeMiddleware`. I am going to lock this issue as the original issue is resolved and what you are asking about is not related.
