### ISSUE TITLE
Copy/paste between flows keeps links to original nodes

### ISSUE THREAD

**Issue by Nenzyz** [node-red/node-red#1158] opened 2017-02-17 10:03 UTC
While copy/paste nodes from one flow (A) to another (B), new node(s) (at B) keep output links from original flow (at A).
How to reproduce:
 - create three node flow, using any nodes: A1 -> A2 -> A3
 - select A2 and press "copy to clipboard" combination
 - paste copied node on a new flow (B) this creates B1 node
 - select B1 with "shift" pressed (selecting all linked flows)
 - press "copy to clipboard", resulting "2 nodes" copied, not one that is selected

In example: node B2 was copied from "Flow A". Inject node "B1" of "Flow B" produces message from "Flow A" node "A3"

[nodered_issue_OutputLinksStays.json.zip](https://github.com/node-red/node-red/files/782860/nodered_issue_OutputLinksStays.json.zip)

**Comment by knolleary** [comment] 2017-02-17 10:05
What version of node-red are you using? This was fixed in 0.16.1

**Comment by Nenzyz** [comment] 2017-02-17 10:13
master branch
17 Feb 10:42:28 - [info] Node-RED version: v0.16.2-git

**Comment by knolleary** [comment] 2017-02-17 10:39
Hmm, I cannot reproduce this on master.

Just to clarify a couple steps, when you say 'copy to clipboard', do you mean the Ctrl/Cmd-C command that copies to the internal clipboard, or the option to export to the system clipboard (Ctrl-E)?

**Comment by Nenzyz** [comment] 2017-02-17 10:46
Combination Ctrl/Cmd-C

**Comment by Nenzyz** [comment] 2017-02-17 10:48
Checked via Menu > Import works correctly

**Comment by knolleary** [comment] 2017-02-17 10:49
Ok... what browser? As I said, I cannot reproduce this following the steps you've provided. But it does look just like a bug we had in 0.16.0 and fixed in 0.16.1.

**Comment by Nenzyz** [comment] 2017-02-17 10:51
Safari - Version 10.0.3 (10602.4.8.0.1)
Chrome - Version 56.0.2924.87 (64-bit)
Both affected.

**Comment by knolleary** [comment] 2017-02-17 10:53
You say you are running from git. Have you run the build task since you last pulled from git?

**Comment by Nenzyz** [comment] 2017-02-17 10:59
Silly me, re-build from using new git clone, everything fine.

**Closed** 2017-02-17 11:00 UTC
