### ISSUE TITLE
http in: invalid JSON request body should result in 400 instead of 500

### ISSUE THREAD

**Issue by rophy** [node-red/node-red#2096] opened 2019-03-15 04:31 UTC
### What are the steps to reproduce?

1. Create a simple flow containing `http in` (POST) and `http out` as below:

```json
[{"id":"7f144795.bc7d2","type":"http in","z":"e2b92b86.d71e7","name":"","url":"/testing","method":"post","upload":false,"swaggerDoc":"","x":220,"y":360,"wires":[["468260b4.ad9fd"]]},{"id":"6d8548.01005ab8","type":"http response","z":"e2b92b86.d71e7","name":"","statusCode":"200","headers":{},"x":580,"y":360,"wires":[]},{"id":"468260b4.ad9fd","type":"change","z":"e2b92b86.d71e7","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"all is good","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":400,"y":360,"wires":[["6d8548.01005ab8"]]}]
```

2. POST /testing with Content-type "application/json" and a valid request JSON body

```
$ curl -i -X POST -H 'Content-Type: application/json' -d '{"hello":"world"}' https://g11n-bot.mybluemix.net/testing
HTTP/1.1 200 OK

all is good
```

3. POST /testing with an invalid JSON request body:

```
$ curl -i -X POST -H 'Content-Type: application/json' -d '{"hello":"world"xxx}' https://g11n-bot.mybluemix.net/testing
HTTP/1.1 500 Internal Server Error

Internal Server Error
```

### What happens?

In step 3, http nodes responded with 500 Internal Server Error

### What do you expect to happen?

In step 3, http nodes should respond with 400 Bad Request, since the error was caused by bad request.
In addition, the response body should explain that request body has invalid syntax, instead of just "Internal Server Error".

### Please tell us about your environment:

- [ ] Node-RED version: v0.19.4
- [ ] node.js version: v8.11.3
- [ ] npm version: v5.6.0
- [ ] Platform/OS: Windows 7
- [ ] Browser: curl

**Comment by knolleary** [comment] 2019-03-15 09:16
Duplicate of #676 - a long standing issue that we haven't been able to get to the bottom of.

**Comment by knolleary** [comment] 2020-10-09 17:24
Closing as its a duplicate - don't need both issues on the list.

**Closed by knolleary** 2020-10-09 17:24 UTC
Labels: duplicate
