### ISSUE TITLE
Blank window in Chrome after returning to NR

### ISSUE THREAD

**Issue by dxdc** [node-red/node-red#2631] opened 2020-07-01 21:47 UTC
### What are the steps to reproduce?

I often leave NodeRed open in the browser as a tab. After upgrading to 1.1.0, returning to a previously opened browser tab yields a completely blank screen. There does seem to be some kind of timeout related to this - e.g., if I wait 5 seconds, this won't happen, but it *will* happen after ~30 minutes.

If I pop open developer tools -- this seems to fix it and it will start working normally again.

### What happens?

Blank screen

### What do you expect to happen?

See my nodes (as with the previous version). I have 151 nodes so the start up is a bit slower now with some changes in the interface. Is it timing something out?

### Please tell us about your environment:

- [ ] Node-RED version: 1.1.0
- [ ] Node.js version: 10.21.0
- [ ] npm version: 6.14.5
- [ ] Platform/OS: macOS (NR is running on Pi, but I suspect not related)
- [ ] Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by knolleary** [comment] 2020-07-01 21:50
Do you mean the workspace is blank, or the entire webpage?

If you have dev tools open at the time, are any errors reported?

I run exclusively with Chrome on Mac and have never seen this behaviour.

**Comment by dxdc** [comment] 2020-07-01 23:10
> Do you mean the workspace is blank, or the entire webpage?

I've seen it both ways. Either a completely white screen, or a workspace with a sidebar, top bar, and no nodes shown inside. I've also seen like a 2-3 second delay of a totally white screen and then it goes back into the normal view. I think there was a difference if I had some nodes open for editing, but not 100% sure.

I'm using a theme, not sure it could be a culprit (?): https://github.com/node-red-contrib-themes/midnight-red

> dev tools open at the time, are any errors reported?

Unfortunately, no.

**Comment by dxdc** [comment] 2020-07-01 23:58
Will post more if I find them:

- [Violation] 'requestAnimationFrame' handler took 66ms
- vendor.js:2 [Violation] Handling of 'mousewheel' input event was delayed for 2449 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by dxdc** [comment] 2020-07-02 13:11
Took 30 seconds from white screen to show nodes this morning. Never saw this issue on the previous version. In the console, I saw this:

chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/polyfill.js:125 Uncaught Error: Extension context invalidated.
    at Object.value [as sendMessage] (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/polyfill.js:125)
    at HTMLDocument.<anonymous> (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js:682)

I'll try Firefox for a few days and see if the behavior is different.

**Comment by dceejay** [comment] 2020-07-02 13:56
what are those chrome extensions ?

**Comment by dxdc** [comment] 2020-07-02 15:12
> what are those chrome extensions ?

- chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/polyfill.js
`This file is part of Adblock Plus <https://adblockplus.org/>`

To rule this out, I just used incognito mode which disables all extensions, but I get the same behavior. Sluggish Node-Red performance, and a lengthy white screen when switching to a tab that has been open for a while previously. By comparison, so far Firefox is lightning fast and doesn't have these issues. I tried updating to the latest version of Chrome (83.0.4103.116 (Official Build) (64-bit)) but no difference.

**Comment by dxdc** [comment] 2020-07-02 21:40
Well, Firefox is causing issues now too.

It seems like something is tying up the main thread, and maybe that's responsible for the behavior I'm seeing. In Chrome, maybe that gives rise to the white screen vs. in Firefox I see all the nodes, but they are completely un clickable. This behavior resolves after some time, which can vary.

I only see this kind of thing after some period of time passes. Otherwise, the behavior is fine. No idea if it's a node causing issues, but all I can say is there was no problem in the prior release. Is there some way to debug this further?

**Comment by knolleary** [comment] 2020-07-02 21:46
When it happens, can you use the Task Manager in Chrome to see what the CPU/Memory usage looks like?

In 1.1.0 we moved to using `requestAnimationFrame` when redrawing the view. So something is definitely going wrong for you - but we've not had any similar reports throughout the beta releases.

In case this is an issue with a particular contrib node, can you share a list of what extra nodes you have installed and that are used in your flows?

**Comment by dxdc** [comment] 2020-07-02 22:43
Thx @knolleary 

Task manager went from 191MB/~0.1% CPU to 110% CPU when I switched tabs. Then after a few seconds it fell back down. I have a 10 core machine w/ 64 GB RAM so it's not like it's system limited....

Installed:

```
    "@node-red-contrib-themes/midnight-red": "^1.4.0",
    "node-red-auth-github": "github:node-red/node-red-auth-github",
    "node-red-contrib-aws": "~0.5.0",
    "node-red-contrib-bigtimer": "~2.3.1",
    "node-red-contrib-blindcontroller": "~4.8.6",
    "node-red-contrib-boolean-logic": "0.0.3",
    "node-red-contrib-boolean-logic-ultimate": "~1.0.17",
    "node-red-contrib-combine": "~1.8.1",
    "node-red-contrib-comfort": "~1.2.0",
    "node-red-contrib-config": "~1.1.3",
    "node-red-contrib-contextbrowser": "0.0.4",
    "node-red-contrib-counter": "~0.1.5",
    "node-red-contrib-credentials": "~0.2.1",
    "node-red-contrib-dsm": "~0.14.1",
    "node-red-contrib-ffmpeg": "~0.1.1",
    "node-red-contrib-google-cloud": "0.0.18",
    "node-red-contrib-homebridge-automation": "0.0.66",
    "node-red-contrib-homekit-bridged": "^1.1.1",
    "node-red-contrib-image-output": "~0.6.3",
    "node-red-contrib-join-wait": "^0.3.5",
    "node-red-contrib-moment": "~3.0.3",
    "node-red-contrib-nbrowser": "~1.1.4",
    "node-red-contrib-npm": "~1.0.2",
    "node-red-contrib-nut-ups": "~1.0.2",
    "node-red-contrib-persist": "~1.0.4",
    "node-red-contrib-play-audio": "~2.5.0",
    "node-red-contrib-schedex": "~1.10.2",
    "node-red-contrib-simple-gate": "~0.3.1",
    "node-red-contrib-sonos-plus": "~4.1.0",
    "node-red-contrib-sonospollytts": "~1.1.25",
    "node-red-contrib-state": "~1.5.0",
    "node-red-contrib-statistics": "~2.2.2",
    "node-red-contrib-string": "~0.2.2",
    "node-red-contrib-sun-position": "~1.1.3",
    "node-red-contrib-sunpos": "~1.4.1",
    "node-red-contrib-time-range-switch": "~1.0.0",
    "node-red-contrib-weekday": "~0.1.0",
    "node-red-dashboard": "~2.22.1",
    "node-red-node-base64": "^0.2.1",
    "node-red-node-discovery": "0.0.22",
    "node-red-node-email": "^1.7.8",
    "node-red-node-exif": "0.0.7",
    "node-red-node-feedparser": "~0.1.16",
    "node-red-node-mysql": "0.1.1",
    "node-red-node-ping": "~0.2.1",
    "node-red-node-prowl": "0.0.10",
    "node-red-node-random": "^0.2.0",
    "node-red-node-rbe": "~0.2.9",
    "node-red-node-serialport": "~0.10.3",
    "node-red-node-smooth": "^0.1.2",
    "node-red-node-sqlite": "~0.4.3",
    "node-red-node-suncalc": "1.0.1",
    "node-red-node-tail": "~0.1.1",
    "node-red-node-timeswitch": "0.0.7",
    "node-red-node-twilio": "~0.1.0"
```

These are not all used, but I can't tell an easy way to figure out which ones are in use.

**Comment by csmale** [comment] 2020-07-03 19:00
I am also seeing this behaviour in Chrome. No amount of F5/refresh will fix the display - I have to open a new tab to get it back.
Just in case it has anything to do with graphics drivers - I am using it in a RDP session.
Although the problem appeared at the time of the upgrade to 1.1.0, I noticed there have been a number of updates to Chrome recently and there might be a connection there?

**Comment by knolleary** [comment] 2020-07-03 19:00
Can you try resizing the window to see if that kicks it?

**Comment by csmale** [comment] 2020-07-03 19:03
> Can you try resizing the window to see if that kicks it?
Will do, I will report back

**Comment by dxdc** [comment] 2020-07-03 19:04
@csmale for me, just opening dev tools got it to come back... maybe try that also

**Comment by knolleary** [comment] 2020-07-03 19:18
Sounds familiar... https://bugs.chromium.org/p/chromium/issues/detail?id=340138

**Comment by dxdc** [comment] 2020-07-03 19:26
@knolleary After sitting on this one a bit long, I think it's actually not Chrome specific. In Firefox I can still see the nodes, but they are totally unresponsive for the same amount of time. Maybe we should retitle the issue to "Unresponsive browser after returning to NR".

I think the main thread is being blocked and the way different browsers handle this is different.

**Comment by knolleary** [comment] 2020-07-03 19:35
At this point, all I can think of is to revert our move to `requestAnimationFrame` for the main drawing of the flows. It had got some us performance benefits in the responsiveness of the UI with large flows - will need to see what the impact will be.

**Comment by dxdc** [comment] 2020-07-04 05:36
Wondering @knolleary, what device are you testing this on? E.g., are you running on a Pi? I'm wondering if that has something to do with it actually. Mine is on a pi. It seems like NR memory and CPU usage has increased but a bit hard to tell.

Once a user clicks on the tab, there is probably some update command being called. On a faster machine you wouldn't notice it, but maybe on a smaller device like a Pi it consumes a huge amount of resources.

**Comment by csmale** [comment] 2020-07-04 07:59
I have just returned to Chrome after leaving it overnight and it is still working! The famous debug effect?
Yesterday I updated a bunch of nodes from "Manage Palette" - which I hadn't done for around two weeks. I don't suppose any of those updates could have affected it? If there's a chance, I will have to dig in to logs etc to find which nodes were updated. Let me know if that might be useful.
If the problem comes back I will try resizing and the dev tools trick.

**Comment by GeorgeCastanza** [comment] 2020-07-06 04:27
I'm getting this as well, as soon as I upgraded to 1.1  
I'm using Chrome, and the Node Red webpage is unresponsive (not necessarily white).  Happy to provide any further details.....

**Comment by knolleary** [comment] 2020-07-07 10:43
For the upcoming 1.1.1 release I've made a couple changes.

1. I've slightly changed the logic around our use of `requestAnimationFrame` to avoid it being overloaded. It's a bit of a theoretical fix - would be interested to hear if it helps.

2. You can disable our use of requestAnimationFrame by opening the devtools window and entering:
    ```
    RED.view.DEBUG_SYNC_REDRAW = true;
    ```

That will only apply for the current session - reloading the page will revert back. But it would be great if anyone still experiences the issue with 1.1.1 could try setting that value and then see if you can recreate. That would help rule in/out the use of requestAnimationFrame as the root cause here.

1.1.1 will be released this week.

**Comment by dxdc** [comment] 2020-07-07 15:20
happy to test when it's out @knolleary

**Comment by knolleary** [comment] 2020-07-08 13:22
1.1.1 has now been published. Please try it out and let me know how you get on.

**Comment by dxdc** [comment] 2020-07-08 14:28
@knolleary so far, it seems like a significant improvement. I'll continue testing over longer time periods and happy to close the issue if you want. Thanks for working to address this one!

Also wanted to share with you two things. This may all be expected due to overall rendering time.

1. This is my dev console on startup (initial load), which takes about 5-10 seconds.
<img width="800" alt="Screen Shot 2020-07-08 at 9 19 40 AM" src="https://user-images.githubusercontent.com/7200365/86930287-77a7d200-c0fc-11ea-83e5-05903112c053.png">

2. This is my dev console on switching between tabs (similar). There is a delay of up to 5 seconds (I have 155 nodes total). There was no difference switching tabs in terms of timing if I mark `RED.view.DEBUG_SYNC_REDRAW = true;`, but the console warnings go away. In fact, it might have been a bit slower after I enabled this... ~20-30% if I had to guess.

<img width="800" alt="Screen Shot 2020-07-08 at 9 16 07 AM" src="https://user-images.githubusercontent.com/7200365/86930411-9a39eb00-c0fc-11ea-8591-710b1564b179.png">

**Comment by walthowd** [comment] 2020-07-09 16:14
NR 1.1.1 fixed this issue for me. I was running latest Chrome x64 build on Linux. Thank you!

**Comment by dxdc** [comment] 2020-07-09 16:26
Having no issues either. Massive difference!

**Comment by knolleary** [comment] 2020-07-13 16:11
Closing as there have been no more reports of issues since 1.1.1 was published.

**Closed by knolleary** 2020-07-13 16:11 UTC
