### ISSUE TITLE
Tweet length still 140

### ISSUE THREAD

**Issue by infontology** [node-red/node-red#1722] opened 2018-05-09 11:24 UTC
### What are the steps to reproduce?

The Twitter node still has 140 characters as limit. 

Update: This is for inbound tweets

### What happens?

msg.payload is truncated at 140 chars

### What do you expect to happen?

All text should be passed through

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment] 2018-05-09 11:27
What version of the node are you using? Looking at the code, version 0.1.13 already changed that limit.

**Comment by infontology** [comment] 2018-05-09 11:34
I use Node-red for IBM Bluemix. It says version 0.18.4

**Comment by hardillb** [comment] 2018-05-09 12:42
Please use the "manage pallet" option to check the actual version of the node-red-node-twitter node.

If you are not at 0.1.13 it should present you with the option to upgrade.

**Comment by infontology** [comment] 2018-05-09 13:43
Thanks for pointing me to the right version number @hardillb 

The Twitter node version number is 0.1.13

However, in the debug panel it says 140 chars, and truncates. It also sends only 140 chars when piping to email node:

tweets/Antitesen : msg.payload : string[140]

**Comment by hardillb** [comment] 2018-05-09 13:46
OK, So this is inbound tweets not sending them?

Also we really should be tracking this against the node-red-nodes repo which actually contains the twitter node...

**Comment by infontology** [comment] 2018-05-09 13:48
Yes, sorry, inbound tweets!

**Comment by infontology** [comment] 2018-05-09 13:49
I updated the first comment, for clarity

**Comment by hardillb** [comment] 2018-05-10 11:34
This is probably down to the underlying library the node uses (twitter-ng). It hasn't been updated since 2014.

There is an outstanding task for somebody (volunteers very welcome) to update the whole Node-RED twitter node.

**Comment by knolleary** [comment] 2018-06-04 22:45
The whole twitter node is in need of massive rework in light of underlying api changes. We have https://github.com/node-red/node-red-nodes/issues/443 open to cover this.

Given that, plus the fact the twitter node is not part of this repository, I'm closing this issue here.

**Closed by knolleary** 2018-06-04 22:45 UTC

**Comment by robertsimione** [comment] 2018-07-17 00:39
I installed Node-Red for the first time yesterday using the quick start instructions in this repo and I am experiencing the same problem.

What are the steps to reproduce?
The Twitter node still has 140 characters as limit.

Update: This is for inbound tweets

What happens?
msg.payload and msg.tweet.text are truncated at 140 chars

What do you expect to happen?
All text should be passed through

Please tell us about your environment:
  Node-RED version: v.0.18.7
  node.js version: v10.6.0
  npm version: 6.1.0
  Platform/OS: MacOS 10.13.5 High Sierra
  Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
