### ISSUE TITLE
Unexpected Node error

### ISSUE THREAD

**Issue by nosehook** [node-red/node-red#3994] opened 2022-12-28 07:07 UTC
### Current Behavior

I frequently have a restart of Node-Red V3.0.2, with one freeze last week.

the report shows:
********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: TCP Timeout after 15000ms
192.168.0.23:9999 {"emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/root/.node-red/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Please report this issue, including the information logged above:
https://github.com/node-red/node-red/issues/
********************************************************************

### Expected Behavior

It seems a plugin is causing the issue.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version: 18.12.1
- npm version: 8.19.2
- Platform/OS: Proxmox LXC with Linux
- Browser: Chrome

**Comment by hardillb** [comment] 2022-12-28 08:01
duplicate of #3954 and #3389 

This is a bug in the node-red-contrib-tplink node and has been raised with them here: https://github.com/caseyjhol/node-red-contrib-tplink/issues/64#issuecomment-1319186881

**Comment by Steve-Mcl** [comment] 2022-12-28 11:03
Closing as this is an upstream node issue and has been raised on the upstream repository. No further action here.

**Closed by Steve-Mcl** 2022-12-28 11:03 UTC
Labels: node
