### ISSUE TITLE
Unable to provide different server name and port for mqtt in and mqtt out nodes

### ISSUE THREAD

**Issue by h-buggi** [node-red/node-red#3988] opened 2022-12-15 13:05 UTC
### Current Behavior

Unable to provide different server name and port for mqtt in and mqtt out nodes. 
The "mqtt in" and "mqtt out" nodes always have the same server and port. 

### Expected Behavior

We should be able to set different broker details for "mqtt" nodes

### Steps To Reproduce

I have the latest build cloned and deployed.

Steps:
1. Add a "mqtt in" node.
2. Add a "mqtt out" node.
3. Edit "mqtt in" node and set server and port number and rest of the details.
4. Edit "mqtt out" node and set different server and port and rest of the details. 
5. Click Deploy

Issue:
The server and port set in step 4 for "mqtt out" node will overwrite and be set on "mqtt in" node as well. If we modily "mqtt in" node - the same server and port will be set on "mqtt out" node.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: Cloned latest build and also verified by deploying using docker compose. 
- Node.js version: v14.18.3
- npm version:6.14.15
- Platform/OS: Linux Ubuntu Ubuntu 20.04.3 LTS and Windows 
- Browser:Chrome

**Comment by Steve-Mcl** [comment] 2022-12-15 13:07
You are essentially editing the same config on 2 different nodes.

You need to add a 2nd broker config

**Comment by Steve-Mcl** [comment] 2022-12-15 13:12
@h-buggi as this is not a bug I will be closing this issue.

If you need further help, please head over to the [node-red forum](https://discourse.nodered.org/) or [slack](https://node-red.slack.com/)

**Closed by Steve-Mcl** 2022-12-15 13:12 UTC
Labels: needs-triage
