### ISSUE TITLE
Join node in manual, create buffer, errors when msg.complete is sent

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#2505] opened 2020-03-14 21:39 UTC
### What are the steps to reproduce?
Run this flow and click the inject to send msg.complete.  
```
[{"id":"7dd2e40e.784e9c","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"8a845493.05c0e8","type":"inject","z":"7dd2e40e.784e9c","name":"BUFFER","topic":"","payload":"[82,73,127,127,128,127,128,127]","payloadType":"bin","repeat":"1","crontab":"","once":true,"onceDelay":0.1,"x":170,"y":80,"wires":[["b41b1253.2afb9"]]},{"id":"de36ad96.67c3a","type":"inject","z":"7dd2e40e.784e9c","name":"COMPLETE","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":120,"wires":[["e6ff2d13.61945"]]},{"id":"b41b1253.2afb9","type":"join","z":"7dd2e40e.784e9c","name":"","mode":"custom","build":"buffer","property":"payload","propertyType":"msg","key":"topic","joiner":"[]","joinerType":"bin","accumulate":false,"timeout":"","count":"","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":570,"y":80,"wires":[["6327aa51.382ec4"]]},{"id":"e6ff2d13.61945","type":"change","z":"7dd2e40e.784e9c","name":"","rules":[{"t":"set","p":"complete","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":120,"wires":[["b41b1253.2afb9"]]},{"id":"6327aa51.382ec4","type":"debug","z":"7dd2e40e.784e9c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":750,"y":80,"wires":[]}]
```

### What happens?
No joined buffer produced and this error is seen in the log:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
    at Function.concat (buffer.js:548:5)
    at completeSend (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/sequence/17-split.js:459:40)
    at JoinNode._inputCallback (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/sequence/17-split.js:667:21)
    at JoinNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:456:21)
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
    at Function.concat (buffer.js:548:5)
    at completeSend (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/sequence/17-split.js:459:40)
    at JoinNode._inputCallback (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/sequence/17-split.js:667:21)
    at JoinNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at processImmediate (internal/timers.js:456:21)
```

### What do you expect to happen?
No error and joined buffer sent

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.4
- [ ] Node.js version: 12.16.1
- [] npm version:  6.13.4
- [] Platform/OS: Ubuntu 19.10
- [] Browser: Waterfox

**Comment by hardillb** [comment] 2020-03-14 21:44
The problem is your second inject node has a date (timestamp) payload as well as the `msg.complete` flag. This can not be merged with the existing buffers.

The solution is to add a rule to the change node to delete the `msg.payload`.

The `msg.complete` flag is intended to be attached to the last message you actually want to be joined.

**Comment by colinl** [comment] 2020-03-14 21:50
Ah yes, you are right, thanks.  However I don't think node-red should error in that way in this circumstance, so there is still a minor issue there.

**Comment by hardillb** [comment] 2020-03-14 21:54
It should error because it can not do what you've asked it to do, which is to merge all incoming messages into a buffer. Now I'll concede that it maybe should raise the error to the editor debug window, so it's more obvious, but the behaviour is right.

**Comment by colinl** [comment] 2020-03-14 21:59
I agree there should be an error, but I assume it should raise an error that can be caught by a catch node.

**Comment by colinl** [comment] 2020-03-14 22:06
A related issue, if a timestamp is fed into a Join node configured as above, but with a timeout specified then node-red crashes when it times out.  Click the Inject button below and wait 5 seconds.
```
[{"id":"fd983380.bb38b8","type":"inject","z":"f06791cf.0adca","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":156,"y":38,"wires":[["1d57a836.d536b"]]},{"id":"1d57a836.d536b","type":"join","z":"f06791cf.0adca","name":"","mode":"custom","build":"buffer","property":"payload","propertyType":"msg","key":"topic","joiner":"[]","joinerType":"str","accumulate":false,"timeout":"5","count":"","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":442,"y":39,"wires":[["fdb1fa6f.05882"]]},{"id":"fdb1fa6f.05882","type":"debug","z":"f06791cf.0adca","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":658,"y":38,"wires":[]}]
```

**Closed** 2020-03-15 16:43 UTC
