### ISSUE TITLE
Subflow enviroment variable name field does not scale properly in UI

### ISSUE THREAD

**Issue by wauswaus** [node-red/node-red#3844] opened 2022-08-15 19:38 UTC
### Current Behavior

If you declare an environment variable for a subflow, the name does not scale properly in the UI.
Declaration view:
![afbeelding](https://user-images.githubusercontent.com/70056029/184704238-e8927439-6fc0-4ae5-994c-5b16ca946401.png)

UI view:
![afbeelding](https://user-images.githubusercontent.com/70056029/184704323-d6fb7b5d-512c-4a8a-889e-b3ddf620b0cc.png)

### Expected Behavior

I would expect that the enviroment variable name field would be scaled to the longest name in the list so the complete variable name is shown.

### Steps To Reproduce

Create a subflow with a long enough enviroment variable

### Example flow

- 

### Environment

- Node-RED version: 3.0.2
- Node.js version: no clue (running as an ass-on in Home Assistant)
- npm version: see above
- Platform/OS: Home assistant Operating System 8.4
- Browser: Firefox 103.0.2

**Comment by knolleary** [comment] 2022-08-15 19:53
Duplicate of https://github.com/node-red/node-red/issues/3651

**Comment by wauswaus** [comment] 2022-08-15 19:57
as mentioned, duplicate.
Sorry for that. Did a quick search in enviroment variables but nothing popped up.

**Closed** 2022-08-15 19:57 UTC
Labels: needs-triage
