### ISSUE TITLE
node-red crashes with empty flows file

### ISSUE THREAD

**Issue by mcflan** [node-red/node-red#824] opened 2016-03-09 17:48 UTC
Platform: raspberry pi 2, raspbian Jessie (uname -a says: Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux)

Background: for reasons unknown (probably powering off at the wrong time,) the flows file (/home/pi/.node-red/flows_raspberrypi.json) was left empty on start-up. On start-up of node-red, the following error occurs and it exits:

```
node-red-pi --max-old-space-size=128 -v
9 Mar 17:17:44 - [info] Node-RED version: v0.13.3
9 Mar 17:17:44 - [info] Node.js  version: v0.10.29
9 Mar 17:17:44 - [info] Linux 4.1.18-v7+ arm LE
9 Mar 17:17:44 - [info] Loading palette nodes
9 Mar 17:17:53 - [info] Settings file  : /home/pi/.node-red/settings.js
9 Mar 17:17:53 - [info] User directory : /home/pi/.node-red
9 Mar 17:17:53 - [info] Flows file : /home/pi/.node-red/flows_raspberrypi.json
9 Mar 17:17:53 - [red] Uncaught Exception:
9 Mar 17:17:53 - SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/lib/node_modules/node-red/red/runtime/storage/localfilesystem.js:202:41
    at /usr/lib/node_modules/node-red/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:272:14
    at /usr/lib/node_modules/node-red/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:107:15)
```

Deleting the empty flows file (or restoring from .node-red/.flows_raspberrypi.json.backup) solves the problem. To reproduce, just create an empty flows file:
```
pi@raspberrypi:~/.node-red $ rm flows_raspberrypi.json 
pi@raspberrypi:~/.node-red $ touch flows_raspberrypi.json 
```

Presumably, no one would intentionally start node-red with an empty flow file. However, since it seems it is possible to do so accidentally (probably due to power failure between saving on re-deploy and syncing the actual disk) perhaps it would be a good idea to catch the error and continue as if starting with no flow file.

**Comment by dceejay** [comment] 2016-03-09 19:09
Duplicate of #819

**Closed by dceejay** 2016-03-09 19:09 UTC
Labels: duplicate
