### ISSUE TITLE
Git commit message with colon fails to show in NR commit history

### ISSUE THREAD

**Issue by hipitihop** [node-red/node-red#3051] opened 2021-07-04 06:00 UTC
![image](https://user-images.githubusercontent.com/4626024/124374651-91183580-dce0-11eb-8d86-c8b05b251456.png)

Above, the history commit items 2,3 & 4 have the word a colon in their commit ie. `broadlink: ....` and do not show the commit message, whereas other do not have the colon.

### What are the steps to reproduce?
Include a colon in commit message e.g. "broadlink: learnt all buttons"

### What happens?
The commit message is not show in the history panel

### What do you expect to happen?
The commit message should be shown

### Please tell us about your environment:

- [x] Node-RED version: v1.3.5
- [ ] Node.js version: 
- [ ] npm version:
- [ ] Platform/OS: Proxmox VM: Ubuntu 20.04 NR via docker-compose
- [ ] Browser: Chrome 87.0.4280.141

**Comment by knolleary** [comment] 2021-07-04 07:39
Duplicate of #3006 

Already fixed. Will be in 1.3.6 and 2.0

**Closed** 2021-07-20 10:56 UTC
Labels: fixed
