### ISSUE TITLE
Web Request when behind a work proxy

### ISSUE THREAD

**Issue by nevercast** [node-red/node-red#353] opened 2014-08-26 23:21 UTC
At work where I am currently using Node-RED for some automation in-house, I am unable to determine how to get Node-RED to work with our firewall, it is a typically HTTP firewall, but I can not find a setting to configure this, nor can I find where in the source web requests are made, so I could not create a PR for this.

I've searched the issues and most other proxy issues seem to be WebSockets related. This is for Web Requests, not the communication between the front and backend of Node-RED itself.

Cheers, and thanks for this beautiful tool.

**Comment by matttrawicki** [comment] 2015-05-12 14:48
:+1: This seems like a cool project; I'm just working my way through the tutorials. Getting stuck on [creating your second flow](http://nodered.org/docs/getting-started/second-flow.html) due to corporate proxy server.

**Comment by dceejay** [comment] 2015-05-13 10:20
@matttrawicki 

thanks for that - actually not totally crude - seems like a minimally intrusive approach. Settings is the right place to put this - only thing I'll change is the settings property names to be more inline with those we already have - ie  httpNodeProxy and httpNodeProxyPort.

That and https traffic needs to be handled slightly more carefully - https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client

Am on the case.

**Comment by dceejay** [comment] 2015-05-13 12:56
Pushed a version of this as  commit 17f3366556de24f24bcc900c32c2511b38a6348d
Supports https via the http proxy also

**Comment by matttrawicki** [comment] 2015-05-15 20:33
Thanks for jumping on the change. Is a similar change necessary for some of the other nodes? As far as testing this change, Node 0.12 had been working for me with 0.10.6 from npm. Cloning master not so happy "TypeError: argument entity must be string, Buffer, or fs.Stats" (https://github.com/node-red/node-red/issues/565). If someone else can verify this change, great, else I can revert back to Node 0.10 next week. At the moment I'm on Windows so no nvm.

**Comment by knolleary** [comment] 2015-05-15 21:50
Yes, any other node that makes http requests under the covers will need to pick up and apply this setting - there isn't a way we can apply it on behalf of nodes.

**Comment by dceejay** [comment] 2015-05-16 16:14
Is this now two issues ? Are you saying the change caused it to break on Node v0.12 ? (which we don't yet support) - or that when you got the git version in order to get the fix something else then broke in v0.12 ?

And then re other nodes - as Nick says there's ot much we can do for all the third party npm modules out there apart from raise issues on their projects... which anyone can do.... - I was thinking that a fairly common idiom is the use of an environment variable http_proxy etc... at the OS level - I have no idea if other nodes that use http under the covers honour that already ? If we find out that a few do - we could also pick that up for our http-request node ? 

Are there any other nodes that we own that we ought to handle ?

**Comment by knolleary** [comment] 2015-05-16 19:43
Any breakage in 0.12 is not a 'new' issue - we've not started looking at 0.12 support yet, so if there were any new breakage, it doesn't count ... ;)

For nodes we maintain, I suspect the WebSocket node in client mode will need looking at, as well as all the social nodes (twitter, and all the web nodes).

**Comment by dceejay** [comment] 2015-05-19 08:59
@matttrawicki  - I've had a change of mind... - I'm reimplementing this to use an external environment variable **http_proxy**  instead of using our settings file - This is because the require npm we use in other nodes (eg Twitter etc) already supports it - so by doing that it "should just work" in more places....
so this change will break you until you set the environment variable at the OS level... and then restart Node-RED eg for Linux
export http_proxy=http://myproxy.co,uk:8080

**Comment by nevercast** [comment] 2015-05-19 09:01
Just thought I'd make a note.
https_proxy is a common environ-var also.

**Comment by dceejay** [comment] 2015-05-19 09:02
exactly... :-) let's use the standard...

**Comment by nevercast** [comment] 2015-05-19 09:05
If we are doing the full implementation, NO_PROXY (no_proxy) is used as a comma separated list of urls/addresses to not use the proxy for. Perhaps there is a module that already obeys these rules? It would be adding one more dependency, but saves rolling your own implementation.

**Comment by elle2** [comment] 2015-05-21 14:25
I've some trouble with a "standard" http_proxy environment variable with username and password, like this:  
http_proxy=http://<username>:<password>@<proxy address>:<proxy port>
Could you help me?  
Thank you

**Comment by hardillb** [comment] 2015-05-21 14:34
@elle2 

You should be able to set username and password as follows:

export HTTP_PROXY=http://user:password@foo.com:8080

(I assume you put something similar to this in but used angle brackets?)

Can you expand a little on what problems you are seeing?

**Comment by elle2** [comment] 2015-05-21 14:38
@hardillb 
Yes I've set username and password like you suggest but using "http request" node with http:www.google.com  I've no valid http response . It's ok if I use the same URL in a browser, so the enviroment variable it's ok.

**Comment by dceejay** [comment] 2015-05-21 16:00
yup... mea culpa... bad regex... will work on it.

**Comment by dceejay** [comment] 2015-05-21 17:02
have pushed a fix that is slightly more relaxed - but am on the road so can't fully test it from here - feedback appreciated.

**Comment by elle2** [comment] 2015-05-22 08:24
I have the same error.
Into console I see: 

MATCH [ 'http://username:password@xxx.xxx.xxx.xxx:8080',
  'http://',
  'username:password@xxx.xxx.xxx.xxx',
  '8080',
  index: 0,
  input: 'http://username:password@xxx.xxx.xxx.xxx:8080' ]

I suppose the issue is with match[2] since there isn't an hostname and I see in tcpdump log several DNS query to resolve an hostname username:password@xxx.xxx.xxx.xxx

**Comment by dceejay** [comment] 2015-05-23 17:57
Thanks for that... pushed another fix - this time letting urllib parse the proxy (which should do a better job than I at picking out the userid:password)

**Comment by knolleary** [comment] 2015-06-14 21:20
Closing as I believe this all works now - will be available in the imminent 0.10.8 release.

**Closed by knolleary** 2015-06-14 21:20 UTC
Labels: enhancement, runtime

**Comment by matttrawicki** [comment] 2015-06-15 20:36
Works great with environment variable. Thanks a ton!

**Comment by stumm101** [comment] 2018-11-05 21:42
Hello,
I'm having a problem similar to the one in this thread.
I have two raspberry pi with raspbian stretch lite, in them is node-network V0.19.4. One raspi I have it in my house, the other one in my work, the one that is in my work I have it behind a web proxy. both are identical except for the latter, the work is after a proxy.
Well, I have a flow inject-> http request-> debug the url of the http node is something like "https://api.telegram.org/bot57:AAElikjZOEMU/sendMessage?chat_id=-2647&text=Test from home"
In the home node-network works perfectly, in the node-network of the work does not work, gives the error: "" Error: tunneling socket could not be established, cause = connect EINVAL 0.0.31.144:80 - Local (0.0.0.0 : 0) ""

I have adjusted the proxy both in the linux system, and in the nodered.service file, but I can not get it to work.
how can I solve that?
