### ISSUE TITLE
Missing icons for some nodes

### ISSUE THREAD

**Issue by machadotiago** [node-red/node-red#1318] opened 2017-07-03 20:33 UTC
After updating to the newest release (17.2) the icons for some nodes are missing. They all became the fallback option: arrow-in.png.

![capture](https://user-images.githubusercontent.com/3775353/27807129-3dd9f404-6015-11e7-8aa5-369302735712.PNG)

I saw this behavior on node-red running on my Mac and also on my Windows.

NPM version: 5.0.4
Node version: 6.10.3
Node-RED: 17.2

**Comment by knolleary** [comment] 2017-07-03 20:51
Hi, we had a similar report of this, which cleared up after a browser restart. The paths used to load node icons changed in 17, so possible the browser is doing some caching?

**Comment by machadotiago** [comment] 2017-07-03 21:00
Nop, unfortunately not. 
Just did a clear installation on a clear Windows 7 Virtual Machine that never had node-red on it and the issue is also there.

**Comment by knolleary** [comment] 2017-07-03 21:05
Hmm odd - a clean install here (and in other places) is working just fine.

What browser are you using? How did you update node-red?

**Comment by machadotiago** [comment] 2017-07-03 21:12
As far as I remember, when I updated last week I just did a 
`npm update -g --unsafe-perm node-red
`
For the Virtual Machine I just booted the Windows 7 for the first time, installed the most recent stable NodeJS, Chrome and then
 `npm install -g --unsafe-perm node-red
`

and saw the same missing icons:
![image](https://user-images.githubusercontent.com/3775353/27807993-15f66282-601b-11e7-99d7-820d32cddd5a.png)

**Comment by Kazuki-Nakanishi** [comment] 2017-07-04 07:41
I reproduced this problem in my environment with a clean install.

The reason is that Node-RED tries to access under {home directory}/.node-red to get email/twitter icons although they are under {Node-RED install directory}/public/icons.

I'll send a pull request to fix this problem soon.

**Comment by knolleary** [comment] 2017-07-04 07:43
Ahhh yes - well spotted. Thanks! I want to get 0.17.3 done this morning, so I look forward to your PR.

**Comment by knolleary** [comment] 2017-07-04 08:04
Closed by #1321

**Closed by knolleary** 2017-07-04 08:04 UTC

**Comment by knolleary** [comment] 2017-07-04 09:22
Node-RED 0.17.3 now available with this fix.
