### ISSUE TITLE
debug node does not respect editor undo

### ISSUE THREAD

**Issue by dennishvo** [node-red/node-red#1621] opened 2018-02-09 22:11 UTC
What are the steps to reproduce?
1. Add a debug node to a flow after some node that produces output and deploy it. You'll see debug output. 
2. Disable the debug node. Note that debug messages cease even before the change is deployed.
3. Now undo (CMD+z on Mac).

What happens?
Debug messages continue to display even though the undo caused the green button on the debug node to appear shaded (off-state). The deploy button, as well, is shaded.

What do you expect to happen?
I expect no change in the state of the debug node until the change is deployed. I also expect the debug node state to be accurately reflected by the shading of the button.

Please tell us about your environment:

- [x] Node-RED version: 0.18.2
- [x] node.js version: 8.9.4
- [x] npm version: 5.6.0
- [x] Platform/OS: Raspberry Pi / linux 4.9.35-v7+ arm LE
- [x] Browser: chrome on Mac OS 10.13.3

**Comment by knolleary** [comment] 2018-02-09 22:18
Hi, thanks for the issue report.

Yes, Ctrl-Z does undo the change of the Debug node state in the editor but it doesn't get reflected in the runtime. That should be fixed.

>I expect no change in the state of the debug node until the change is deployed.

Clicking the button on the debug node is expected to change the debug node state without a deploy. That is intended behaviour.

**Comment by knolleary** [comment] 2020-10-09 17:10
This was fixed in a recent release.

**Closed by knolleary** 2020-10-09 17:10 UTC
Labels: node
