### ISSUE TITLE
Delay Node endlessly upping time

### ISSUE THREAD

**Issue by mobamoba** [node-red/node-red#4760] opened 2024-06-13 13:32 UTC
### Current Behavior

Because pictures is worth a thousand

https://github.com/node-red/node-red/assets/11135869/bac2b185-4b00-4935-bc2d-c224448101bc

 words, I've attached a video showing what was going on. I've never seen this behavior before nor was I doing anything strange - literally I just dragged in a Delay node and set it for 10 minutes and that was it.

### Steps To Reproduce

No idea as I have no idea why this happened at all.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.10
- Node.js version: 20.5.0
- npm version: 9.8
- Platform/OS: Ubuntu 20.04.6 LTS
- Browser: Firefox

**Comment by hardillb** [comment] 2024-06-13 14:24
Could you add some more descriptions please, the video won't play for me in either chrome or firefox

**Comment by knolleary** [comment] 2024-06-13 14:31
@mobamoba is this all Delay nodes or just this one in particular? Are you passing lots of messages to it or just one? Any more context you can provide would be helpful. Your video does should the number going up, but without any more information about the flow, it's not a lot to go on.

**Comment by Steve-Mcl** [comment] 2024-06-14 09:16
@mobamoba the status is a count of messages queued.

It looks to me like you have an uncontrolled loop in your flows.

This is easy to prove by adding a debug node BEFORE the delay node.

Demo

![slack_yUY2ZGiugU](https://github.com/node-red/node-red/assets/44235289/f9e27ec0-c342-4901-864f-9c9d4dcd8f2b)

**Comment by mobamoba** [comment] 2024-06-14 13:45
I understand, but the reason I was reporting it as a bug is that when I deleted the Delay node and simply replaced it with a new one for the exact same amount of time in the exact same place in the flow with no other changes, it worked fine and exactly as expected with the status count operating as expected.

**Comment by Steve-Mcl** [comment] 2024-06-14 23:51
That would depend on what type of deploy you did (full deploy? Flow deploy? Modified node deploy?)

If you did full or modified flow deploy you will interrupt the loop and all wueued messages in the replaced delay node are destroyed. 

The condition in your flow that triggers the loop will likely return when the right conditions are met. 

As far as I can see, this is a flow design issue not a bug.

**Comment by Steve-Mcl** [comment] 2024-06-15 10:56
@mobamoba I am 99% certain you just have a latent issue in your flows that upon certain conditions, causes an uncontrolled message loop. 

Off the top of my head: if you did a "modified flows" deploy that reset internal state of a node that was meant to "control your loop" and messages are still in transit (via MQTT/link nodes/etc), it may be possible to get into this situation. But that in its self is the reason I always try to convince users of NR not to create loops as they can lead to uncontrolled loops and there is almost always a "better way" than having a loop in your flows - but TBH, the Node-RED forum is the right place to discuss that sort of thing anyhow.

I will close this issue for now but please feel free to re-open it if you can produce a repeatable demo a set of steps that recreate the issue you are seeing.

**Closed by Steve-Mcl** 2024-06-15 10:56 UTC
Labels: needs-triage
