### ISSUE TITLE
Can't enable redirect HTTPS and possible typo on settings.js

### ISSUE THREAD

**Issue by bigbang55** [node-red/node-red#1914] opened 2018-10-03 03:52 UTC
### What are the steps to reproduce?

1. enable *requireHttps: true* in the *settings.js*
2. enable https: { } and add private key/certificate
3. start node-red

### What happens?

HTTPS works fine, but when using HTTP I'm not being redirected to HTTPS. Also the commented *requireHttps: true* in the base *settings.js* is missing a comma.

### What do you expect to happen?

Accessing http://example.com:1880 to redirect me to https://example.com:1880

### Please tell us about your environment:

- [ ] Node-RED version: v0.19.4
- [ ] node.js version: v10.11.0
- [ ] npm version: v6.4.1
- [ ] Platform/OS: Ubuntu 18.0.4
- [ ] Browser: Google Chrome

**Comment by hardillb** [comment] 2018-10-03 07:10
This is working as intended, you can't have a redirect on the same port (both your examples are running on port 1880)

**Comment by knolleary** [comment] 2018-10-07 07:41
Closing as per the comments from @hardillb

**Closed by knolleary** 2018-10-07 07:41 UTC
