### ISSUE TITLE
Node status updates seem to ignore/escape `\n`

### ISSUE THREAD

**Issue by spdustin** [node-red/node-red#1728] opened 2018-05-17 21:42 UTC
### What are the steps to reproduce?
In a function node, write:
```javascript
node.status({text:'I am a\nmultiline\nstatus'});
```
### What happens?
Actual output of node's status label:
> I am a\nmultiline\nstatus
### What do you expect to happen?
Expected output of node's status label:
> I am a
> multiline
> status
### Please tell us about your environment:

- [ ] Node-RED version: 0.18.6
- [ ] node.js version: 10.1.0
- [ ] npm version: 6.0.1
- [ ] Platform/OS: Ubuntu 16.04.4 LTS
- [ ] Browser: Safari 11.1.1 and, well, pretty much all of the latest builds of Firefox and Chrome

**Comment by knolleary** [comment] 2018-05-17 21:44
Node status does not support multiple lines. That is by design.

**Comment by hardillb** [comment] 2018-05-17 21:44
The editor is not meant to be a dashboard, status are not really intended long messages.

**Comment by dceejay** [comment] 2018-05-18 09:47
closing as it's working as designed.

**Closed by dceejay** 2018-05-18 09:47 UTC
Labels: wontfix
