### ISSUE TITLE
Function node - unable edit function on mobile/tablet

### ISSUE THREAD

**Issue by pawelfiedor** [node-red/node-red#1163] opened 2017-02-20 11:28 UTC
I'm unable to edit function code on tablet or mobile (tested on Android, latest Chrome and Firefox). It is not possible to edit. Strange things happens. When try to input text only last character change or deletes. I thing it is ACE editor issue.

**Comment by ristomatti** [comment] 2017-05-18 16:41
@pawelfiedor I noticed the same but this is most likely an issue with the integrated Ace editor than Node-RED itself. As a workaround, another virtual keyboard can be used. For example [Hacker's Keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en) does not suffer from this issue.

**Comment by Steve-Mcl** [comment] 2022-02-07 13:47
As @ristomatti states, the issue is with the keyboard. I can verify using a more basic or hackers keyboard this issue is not present.

Closing thread for now. If you  still experience this issue, please re-open.

**Closed by Steve-Mcl** 2022-02-07 13:47 UTC
