### ISSUE TITLE
Node-RED v 0.13.2 HTTP In node bug

### ISSUE THREAD

**Issue by djthequest** [node-red/node-red#808] opened 2016-02-26 07:31 UTC
http in node: OK button is not working. It gives a javascript error. I have attached a screenshot for the same.
After I click Cancel button, the new edits gets saved and things work fine.

**Comment by knolleary** [comment] 2016-02-26 07:50
Hi, looks like the screenshot got missed off.

**Comment by djthequest** [comment] 2016-02-26 17:17
![screenshot 2016-02-26 12 59 15](https://cloud.githubusercontent.com/assets/5879102/13359559/ef05141c-dcda-11e5-9da4-9ed46ba7dd80.png)

**Comment by knolleary** [comment] 2016-02-26 17:18
How did you install node-red?
Have you got the swagger node installed as well?

**Comment by djthequest** [comment] 2016-02-26 17:35
Downloaded, extracted and did npm production install

On Fri, Feb 26, 2016 at 10:49 PM, knolleary <notifications@github.com>
wrote:

> How did you install node-red?
> Have you got the swagger node installed as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-red/node-red/issues/808#issuecomment-189379162>.
>



-- 
*Dibyanshu Jaiswal*
Mb: +91 9038304989

**Comment by knolleary** [comment] 2016-02-26 21:33
What file did you download and from where exactly?
Did you replace an existing installation? If so, how did you do it (extract over the top, move sideways,...?)
And do you have the swagger node installed?

**Comment by knolleary** [comment] 2016-03-02 19:58
Hi - we need to understand exactly what steps you took to upgrade that led to this. Otherwise there's not much we can do.

**Comment by djthequest** [comment] 2016-03-07 11:04
I downloaded the file

https://github.com/node-red/node-red/releases/download/0.13.3/node-red-0.13.3.zip

Then did

npm install --production

That's all I did


On Thu, Mar 3, 2016 at 1:28 AM, knolleary <notifications@github.com> wrote:

> Hi - we need to understand exactly what steps you took to upgrade that led
> to this. Otherwise there's not much we can do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-red/node-red/issues/808#issuecomment-191401352>.
>



-- 
*Dibyanshu Jaiswal*
Mb: +91 9038304989

**Comment by dceejay** [comment] 2016-03-08 11:08
You need to complete the development install instructions - For Development - from GitHub section of http://nodered.org/docs/getting-started/installation
you need to go into the node-red directory and run grunt build before running

**Comment by knolleary** [comment] 2016-03-08 12:01
I cannot reproduce this at all.

In a clean directory, can you run:

   $ npm install node-red
   $ node node_modules/node-red/red.js

to run a cleanly installed version and see if you still hit this error?

**Comment by knolleary** [comment] 2016-07-03 22:03
Hi, any news on this? Have you tried a reinstall?

**Comment by knolleary** [comment] 2017-01-09 22:51
Closing - if this is still an issue, please reopen with any further details.

**Closed by knolleary** 2017-01-09 22:51 UTC
Labels: node
