### ISSUE TITLE
Node red not throwing error on start even if PORT is already in use

### ISSUE THREAD

**Issue by bharathhs2290** [node-red/node-red#1892] opened 2018-09-20 11:15 UTC
### What are the steps to reproduce?
1. install node js & node red version  v0.18.7
2. Run express or similar server on port 1880, verify server is running on 1880
3. now start node-red 
### What happens?
node-red starts with port 1880 and can be accessed at 127.0.0.1:1880 , without throwing port occupied error
### What do you expect to happen?
node-red should throw error , as port 1880 is already occupied by express server
### Please tell us about your environment:

- [ v0.18.7 ] Node-RED version:
- [v8.11.1 ] node.js version:
- [5.6.0 ] npm version:
- [windows 7 ] Platform/OS:
- [ google crome ] Browser:

**Comment by knolleary** [comment] 2018-09-20 15:21
Node-RED doesn't contain any code that allows it to take over a port that is already in use - to be honest, I'm not sure if any operating system would allow that happen. 

If I run two instances of node-red, the second one fails to start with a port-in-use error.

Can you share the source of the app you are running on port 1880 so we can try to recreate?

**Comment by knolleary** [comment] 2019-01-17 22:47
Closing this issue as no further information has been provided and we cannot reproduce. Please reopen with more information as requested if this remains an issue for you.

**Closed by knolleary** 2019-01-17 22:47 UTC
Labels: needs-info
