### ISSUE TITLE
Enabling es6 by default for the editor.

### ISSUE THREAD

**Issue by hrandib** [node-red/node-red#985] opened 2016-09-11 01:23 UTC
Is it possible to enable es6 by default somewhere in the options?

**Comment by dceejay** [comment] 2016-09-11 07:16
Es6 capability is determined by the underlying version of node.js, so is up to the user. We currently recommend version 4.x LTS . But debian and raspbian (on the Pi) still include v0.10 (which is beyond end of life). 

There is a command line flag you can use to include "more" of es6 , see https://nodejs.org/en/docs/es6/ and you can pass that through to node see the passing arguments section of http://nodered.org/docs/getting-started/running

**Comment by hrandib** [comment] 2016-09-11 08:55
Hello, Dave.
Thank you. But in my configuration es6 features works fine (node.js v6.5). I wrote about editor in the function node. It treats as warnings es6 code. How do I pass parameters to jshint? Current workaround for me is:
1. '// jshint esversion: 6' in every function node
2. Direct edit of worker-javascript.js in the public/vendor/ace folder
Both are ugly.

**Comment by dceejay** [comment] 2016-09-11 08:58
Ah... much clearer what the issue is :-)

**Comment by knolleary** [comment] 2016-09-30 22:52
Fixed in 0.15.0 branch

**Closed by knolleary** 2016-09-30 22:52 UTC
