### ISSUE TITLE
Node red bluemix twitter: "Unauthorized"

### ISSUE THREAD

**Issue by DaviGuanabara** [node-red/node-red#1093] opened 2016-12-20 13:29 UTC
When i click the button "click here to authenticate with twitter", inside twitter output node > Edit twitter-credentials node, on IBM Bluemix Node-Red, im redirected to this link:

https://natiar.mybluemix.net/red/twitter-credentials/c21ab585.fa4938/auth?callback=https%3A%2F%2Fnatiar.mybluemix.net%3A%2Fred%2Ftwitter-credentials%2Fc21ab585.fa4938%2Fauth%2Fcallback

that throws a single word:

> Unauthorized

*i tried Google Chrome with Android and Google Chrome and Safari with OS X El Capitan 10.11.6, but the "Unauthorized" appeared in all cases.

**Comment by knolleary** [comment] 2016-12-20 13:30
Duplicate of https://github.com/node-red/node-red-nodes/issues/253

**Closed by knolleary** 2016-12-20 13:30 UTC
