### ISSUE TITLE
Time exceeds 24:00

### ISSUE THREAD

**Issue by cg089** [node-red/node-red#3810] opened 2022-07-29 00:10 UTC
### Current Behavior

Status messages shows time later than 24:00, in this case 24:47:45
![nodered-time](https://user-images.githubusercontent.com/12937900/181657073-909f50b9-6d51-496d-bbd8-62bb75c4afe5.JPG)

### Expected Behavior

In 24-hour-clock the time starts at midnight 0:00 and goes up to 23:59:59. The next second is 0:00, in some cases also said as 24:00.

24:00 is the last second of the day, then the next day begins at 0:00. There is no 24:01 or later.

### Steps To Reproduce

Check status - delay 1 msg/day - last message between midnight and 1 am.

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 13.3.0
- Node.js version: v16.16.0
- npm version:
- Platform/OS: Linux 5.15.55 x64 LE (HaOS 8.4 / 2022.7.7)
- Browser: Chrome

**Comment by knolleary** [comment] 2022-07-29 00:17
Those look like HomeAssistant nodes. This repository is for the core Node-RED project. We do not maintain the HA nodes. You will need to report this issue in their GitHub repo for them to look at.

**Comment by Steve-Mcl** [comment] 2022-07-29 09:27
Looking at your comment `Node-RED version: 13.3.0` I am certain this is node-red inside "Home Assistant" 
Node-Red current version is `3.0.1` 
Additionally, those _blue_ nodes are not core node-red.

As Nick has advised, you will need to first speak with the Home Assistant guys as the status those nodes display will be generated by their own internal code.

I will close this issue and mark it as upstream for now.

Please raise an issue on the HA repository and link back to this issue for other users to track its progress and if it turns out that the issue is somehow due to node-red core, we can re-open this.

**Closed by Steve-Mcl** 2022-07-29 09:27 UTC
Labels: upstream
