### ISSUE TITLE
Node-red github integration crashes with wrong credentials

### ISSUE THREAD

**Issue by javaknight** [node-red/node-red#1715] opened 2018-05-01 18:17 UTC
<!--

### What are the steps to reproduce?
1. Setup a private github integration with node-red
2.  (OPTIONAL) Provide it with the right credentials. Validate push works, etc
3.  Node-red will forget those credentials, unless you told it to save them, later on
4. Put in the wrong credentials
5. Node-red gets confused.. You'll see an errror in the log as well
6. Issue cannot be resolved until you restart node-red. You won't get prompte to input the right credentials ever again.
### What happens?
Node-red refuses to allow further access to github private repo.
### What do you expect to happen?
Node-red doesn't crash
### Please tell us about your environment:

- [ ] Node-RED version: 0.18.4
- [ ] node.js version: 
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by hardillb** [comment] 2018-05-01 20:04
Please at least fill in the template (that you've deleted) with the versions, because as it stands this issue is practically useless

**Comment by knolleary** [comment] 2018-05-01 20:06
@hardillb this was raised at my request on slack... but yes, it does need details adding as the description alone is not clear of the scenario.

**Comment by knolleary** [comment] 2018-05-02 13:09
@javaknight please provide the steps needed to reproduce this as I cannot get it to fail.

What specific action are you taking when it prompts for username/password?

For example, having added a new remote, I click the 'select remote branch' button and it prompts me for user/pass. I mistype them, it prompts me to try again.

But there are a few other actions that cause it to prompt for credentials if it doesn't already know them - it may simply be one of them doesn't prompt properly in the case of an auth failure. But without more details to narrow it down, we'll be wasting our time trying to figure out the scenario you mean.

**Comment by knolleary** [comment] 2018-05-02 13:13
Also, what version of node-red are you using? There were a couple issues like this in earlier 0.18 releases, none I know of in 0.18.4

**Comment by knolleary** [comment] 2018-05-17 10:37
@javaknight I know I asked you to raise these issues so we wouldn't forget about them, but without any of the information we've asked for there is little point keeping them open. Please let us know if you are able to provide the additional information, otherwise we'll close the issue.

**Comment by knolleary** [comment] 2018-06-04 22:46
Given the lack of response after multiple requests, I'm closing this issue. Please reopen with the additional information if you are able to provide it.

**Closed by knolleary** 2018-06-04 22:46 UTC
Labels: needs-info
