### ISSUE TITLE
Node-RED dies with "assertion failed" in libuv ?

### ISSUE THREAD

**Issue by vielmetti** [node-red/node-red#601] opened 2015-03-28 04:04 UTC
I'm running this:

```
Darwin edwards-air 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
OS X 10.9.5
27 Mar 23:51:33 - [info] Node-RED version: v0.10.4
27 Mar 23:51:33 - [info] Node.js  version: v0.10.35
```
and after some period of time running, node crashes unexpectedly with
```
Assertion failed: (uv__has_active_reqs(req->loop)), function uv__queue_done, file ../deps/uv/src/unix/threadpool.c, line 236.
Abort trap: 6
```

It seems to be coming from libuv, related to this discussion

https://groups.google.com/forum/#!topic/libuv/2ia9S7wuZX0

I'm going to post something similar to http://github.com/libuv/libuv and see what they know about it.

**Comment by knolleary** [comment] 2015-03-28 07:51
By my reading of that libuv mailing list post you point at, this may be caused by an incorrect usage of a particular libuv api.

We have no native code in node-red, so the issue will not be in our code base, nor one that we can do anything about.

It is most likely coming from one of the node module dependencies that contains native node. What nodes are you using?

**Comment by vielmetti** [comment] 2015-03-28 13:11
The particular test setup was getting a steady stream of events from a sensortag. That means its dependencies include the Bluetooth BLE stack on the Mac, plus 'noble', 'node-sensortag', and 'node-red-node-sensortag'. Since I'm working on all those things right now to port ths sensortag 2 support, I'm sure I have a round of component updates to do.

**Comment by vielmetti** [comment] 2015-03-28 13:24
Digging further through the source it looks like the libuv code is in the `node-xpc-connection` module, https://github.com/sandeepmistry/node-xpc-connection , which is in turn pulled in by `noble`. I'm not completely clear on all of the dependencies and versions that I'm running. Perhaps @sandeepmistry can shed some light on this.

**Comment by vielmetti** [comment] 2015-03-28 13:26
The flow I am running is very simple, the gist of it is here. 

https://gist.github.com/1d3a3bbd34ee47081606

**Comment by sandeepmistry** [comment] 2015-03-28 18:19
@vielmetti I haven't experienced this issue.

Please open an issue in the node-xpc-connection repo. It would be great if you had something to reproduce it outside of node-red. [libuv API usage is fairly isolated](https://github.com/sandeepmistry/node-xpc-connection/blob/master/src/XpcConnection.cpp#L64), let me know if it's doing anything incorrectly.

**Comment by knolleary** [comment] 2015-03-28 20:03
As this isn't going to lead to any code changes in this repository, and you've created an issue to track the problem with the module believed to be the cause, I'm going to close this issue.

**Closed by knolleary** 2015-03-28 20:03 UTC
Labels: upstream

**Comment by vielmetti** [comment] 2015-03-30 13:40
Thanks @knolleary . A contributor noted the underlying problem (some code in libuv is not thread-safe).
