### ISSUE TITLE
Since 0.20 Crash on Full Deploy

### ISSUE THREAD

**Issue by soloam** [node-red/node-red#2105] opened 2019-03-22 11:50 UTC
### What are the steps to reproduce?

In my flows when I do a full deploy my nodered crashes

### What happens?

Nodered crashes in full deploy

### What do you expect to happen?

No crash and deploy

### Please tell us about your environment:

-  Node-RED version: v0.20.3
-  node.js version: v8.15.1
-  npm version: 6.4.1
-  Platform/OS: FreeBSD (FreeNAS 11.2 Jail)
-  Browser: Linux Debian Chrome 72.0.3626.96 (Official Build) (64-bit)

Logs:
```

22 Mar 11:45:37 - [debug] saved flow revision: 00362144fe8c89eda2c7ca35b0d7a3bb
22 Mar 11:45:37 - [info] Stopping flows
22 Mar 11:45:37 - [debug] red/nodes/flows.stop : stopping flow : global
22 Mar 11:45:37 - [debug] red/nodes/flows.stop : stopping flow : 4a15ab3.3bee654
22 Mar 11:45:37 - [debug] red/nodes/flows.stop : stopping flow : 4033059a.fb544c
22 Mar 11:45:37 - [debug] red/nodes/flows.stop : stopping flow : 4c79763b.db0a88
22 Mar 11:45:37 - [debug] red/nodes/flows.stop : stopping flow : a82bb95.1d8c548
22 Mar 11:45:37 - [info] [mqtt-broker:MQTT Main] Disconnected from broker: mqtt://debian.myhome:1883
22 Mar 11:45:37 - [info] [mqtt-broker:MQTT IOT] Disconnected from broker: mqtt://192.168.7.20:1883
22 Mar 11:45:37 - [info] [mqtt-broker:MQTT Internal] Disconnected from broker: mqtt://localhost:1883
22 Mar 11:45:37 - [info] [mqtt-broker:MQTT IOT] Disconnected from broker: mqtt://192.168.7.20:1883
22 Mar 11:45:40 - [info] Stopped flows
22 Mar 11:45:40 - [info] Starting flows
22 Mar 11:45:40 - [debug] red/nodes/flows.start : starting flow : global
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : f5733254.6f51e
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 669ce134.dd658
22 Mar 11:45:40 - [debug] red/nodes/flows.start : starting flow : 4a15ab3.3bee654
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : d0e147ec.9176b8
22 Mar 11:45:40 - [debug] red/nodes/flows.start : starting flow : 4033059a.fb544c
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : e0373704.874498
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 13bcf39d.60ba5c
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 5e80526.2930dac
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 571042be.0d7c5c
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 36a3c047.a610b
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 9e31383f.9f04c8
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : b7a662f6.8ee27
22 Mar 11:45:40 - [debug] red/nodes/flows.start : starting flow : 4c79763b.db0a88
22 Mar 11:45:40 - [debug] red/nodes/flows.start : starting flow : a82bb95.1d8c548
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : a2ddc455.980dc8
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : 6f2120c2.484b9
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : b0b12b19.08a808
22 Mar 11:45:40 - [debug] red/nodes/flows.start : not starting disabled flow : acc85c31.0538f
```
 And sometimes
```

<--- Last few GCs --->

[56781:0x805c31680]   407516 ms: Mark-sweep 1404.5 (1578.4) -> 1404.5 (1578.4) MB, 1302.7 / 0.1 ms  allocation failure GC in old space requested
[56781:0x805c31680]   408946 ms: Mark-sweep 1404.5 (1578.4) -> 1404.5 (1531.9) MB, 1429.1 / 0.2 ms  last resort GC in old space requested
[56781:0x805c31680]   410256 ms: Mark-sweep 1404.5 (1531.9) -> 1404.5 (1531.9) MB, 1310.5 / 0.3 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3da7167a58b9 <JSObject>
    1: new constructor(aka FunctionNode) [/usr/local/lib/node_modules/node-red/node_modules/@node-red/nodes/core/core/80-function.js:~56] [pc=0x442a7feea52](this=0x3f07395a3919 <FunctionNode map = 0x3ac711b2ff91>,n=0x3f07395a3621 <Object map = 0x2c3b19b30149>)
    3: createNode [/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:~468] [pc=0x442a7fc4b56](t...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort(void) [/usr/local/bin/node]
 2: node::FatalError(char const*, char const) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 6: v8::internal::WeakFixedArray::Allocate(v8::internal::Isolate*, int, v8::internal::Handle<v8::internal::WeakFixedArray>) [/usr/local/bin/node]
 7: v8::internal::WeakFixedArray::Add<v8::internal::HeapObject> v8::internal::WeakFixedArray::Add(v8::internal::Handle<v8::internal::Object>(int*) [/usr/local/bin/node]
 8: v8::internal::Factory::NewSharedFunctionInfo<v8::internal::Code> v8::internal::Factory::NewSharedFunctionInfo(v8::internal::MaybeHandle<v8::internal::String>(bool, v8::internal::FunctionKind) [/usr/local/bin/node]
 9: v8::internal::MaybeHandle<v8::internal::Name> v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(v8::internal::Isolate*, v8::internal::Handle<v8::internal::FunctionTemplateInfo>() [/usr/local/bin/node]
10: v8::internal::Isolate*<v8::internal::Object> v8::internal::ApiNatives::CreateApiFunction(v8::internal::Isolate*, v8::internal::Handle<v8::internal::FunctionTemplateInfo>(v8::internal::ApiNatives::ApiInstanceType, v8::internal::MaybeHandle<v8::internal::Name>) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Name> v8::internal::ApiNatives::InstantiateFunction(v8::internal::Handle<v8::internal::FunctionTemplateInfo>() [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Name> v8::internal::ApiNatives::InstantiateFunction(v8::internal::Handle<v8::internal::FunctionTemplateInfo>() [/usr/local/bin/node]
13: char const* v8::internal::InstallFunc(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>(void(*)(v8::FunctionCallbackInfo<v8::Value> const&), int) [/usr/local/bin/node]
14: v8::internal::WasmJs::Install(v8::internal::Isolate*) [/usr/local/bin/node]
15: v8::internal::Genesis::InstallSpecialObjects(v8::internal::Handle<v8::internal::Context>) [/usr/local/bin/node]
16: v8::Local<v8::ObjectTemplate> v8::internal::Bootstrapper::CreateEnvironment(v8::internal::MaybeHandle<v8::internal::JSGlobalProxy>(v8::ExtensionConfiguration*, unsigned long, v8::DeserializeInternalFieldsCallback, v8::internal::GlobalContextType) [/usr/local/bin/node]
17: v8::ExtensionConfiguration*<v8::Value> v8::NewContext(v8::Isolate*, v8::ExtensionConfiguration*, v8::MaybeLocal<v8::ObjectTemplate>(unsigned long, v8::DeserializeInternalFieldsCallback) [/usr/local/bin/node]
18: v8::ExtensionConfiguration*<v8::Value> v8::Context::New(v8::Isolate*, v8::ExtensionConfiguration*, v8::MaybeLocal<v8::ObjectTemplate>() [/usr/local/bin/node]
19: _register_contextify(void) [/usr/local/bin/node]
22 Mar 11:41:16 - [info] 

```

In my top I see WCPU over 100%

Thank you

**Comment by dceejay** [comment] 2019-03-22 12:14
sounds like you have a loop... 
try starting Node-RED in safe mode
 
    node-red --safe

which will start the editor without running the flows - then you may be able to identify and fix the lop before deploying again.

**Comment by soloam** [comment] 2019-03-22 12:29
If that is the case, what is the reason to only happen in deploy? And not in reboot? And when I was in 0.19 it did not happen

**Comment by dceejay** [comment] 2019-03-22 12:36
maybe something is not closing down properly ? some extra node installed ? If they don't close down properly they may leave objects in memory such that you then run out next time start and you get that second crash.

**Comment by knolleary** [comment] 2019-03-22 13:19
The key point here is it's an out of memory issue. The stack trace you've provided doesn't tell us anything about what is consuming the memory. If you've made no material changes to your flows since upgrading, then we need to identify what about your flows is causing this behaviour that we don't see elsewhere.

The only way we can do that is if you are able to provide full details of your flows. That log shows you have quite a few tabs, many of which are disabled. There's quite a task to narrow down which node or set if nodes is causing this.

**Comment by soloam** [comment] 2019-03-22 15:21
Hello, the reason to have so many disabled tab's is to try no find what is causing this! But so far no conclusion. 

I did not changed nothing to my flows since I have updated! 

The main thing that I have in my flows, is a lot of subflows... nested subflows! And I notice that this mostly occurs when I change a subflow! 

The main change in 0.20 is Subflows! So can this be related?

**Comment by knolleary** [comment] 2019-03-22 15:23
It could be related. It would really help if, like I asked, you can provide full details of your flows. Just saying 'lots of subflows' doesn't really help narrow anything down.

**Comment by soloam** [comment] 2019-03-22 15:28
I would like to share the flows, but without detecting the flow that is giving problems, it's impossible to share everything... Would you like to enter my system by teamviewer to se if you can spot anything that can be helpful?

**Comment by soloam** [comment] 2019-03-22 15:47
Ok I noticed that the problem does not seams to be related to a specific tab, but with the number of tabs! I disabled some of them, randomly, and I'm able to Fully Deploy! Is there a way to raise the allowed memory to nodered to see if that solves the problem? Until the actual problem is detected?

**Comment by dceejay** [comment] 2019-03-22 15:58
How are you starting it ? How much memory does the NAS have ?
There is a node-red-pi script we use to start it on constrained machines which we use to help pass in extra options like  `--max_old_space_size=256`
which limits it to 256MB .. though it should be noted it's not a hard limit - it's more like a flag for when the garbage collector cuts in... . so it can go higher...

**Comment by soloam** [comment] 2019-03-22 16:03
RAM is not a problem on my server! I have 32GB RAM, and I'm using 10GB

**Comment by dceejay** [comment] 2019-03-22 16:16
Not one I recognise (not being a NAS user), but presumably it possibly constrains how much space you can use per extra task somehow (I think I saw it uses jails ??) - and if so then either that needs to be relaxed - or the --max_old_space flag needs to be set appropriately to help match it.

I suspect you may be better asking this question on the discourse forum where there are more likely to be NAS users in the wider community.

**Comment by soloam** [comment] 2019-03-22 16:20
This is a FreeBSD Jail, no limitation... I used this for a long time, only now I'm having this problem... If I roll back to 0.19 the problem is solved! But I didn't want to do that

**Comment by soloam** [comment] 2019-03-22 16:22
This is my top 

```
  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
46350 nodered      10 103    0  2147M  1592M CPU2    2   3:46  99.61% node
```
The memory consumption keeps rising until it crashes

```
 PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
46350 nodered      10 103    0  2170M  1615M CPU3    3   4:56 108.54% node
```

**Comment by knolleary** [comment] 2019-03-22 16:26
Does it rise of its own accord or only when you hit deploy?

Can you try to provide some concrete details about your flows? How many? How many subflow instances? You mentioned you have them nested? To what degree? How many? How deep? Give us a more concrete sense of what you have.

**Comment by soloam** [comment] 2019-03-22 17:37
It rises when I deploy!
 
My main flow's is to manage devices, receives and sends several MQTT messages. The flows contain around 12 nodes nested between them, The top is 5 deep!

This flows are working without a problem in 0.19, only when I updated to the 0.20 the problem started. I tested with a update and with a fresh install, and copy flows, both with the same errors! The node and npm version are the same in both of them.

**Comment by soloam** [comment] 2019-03-22 17:50
I tested back 0.19.5, the exact same flows Fully Activate in around 10 seconds, no crash at all

**Comment by knolleary** [comment] 2019-03-22 21:56
I have a test flow with 5 tabs, each with 3 or 4 subflows, and a couple of those subflows have multiple nested subflows.

Having enabled the 'metrics' log level, I'm capturing the heapUsed and heapTotal - and both remain pretty stable as I deploy changes.

I think we're going to need you to dig into this to try to isolate the cause. Or if you can provide a much more detailed break down of your flows so we can try to reproduce that would help. It would also help to share what non-core nodes you are using.

**Comment by soloam** [comment] 2019-03-25 10:28
I will make a new copy instance of nodered and start removing nodes until I can deploy it! And try to check what is causing this problem.

Thank You

**Comment by soloam** [comment] 2019-04-02 00:26
Ok, I think I solved my problem, for now, with a change to the start of nodered

**Comment by knolleary** [comment] 2019-04-02 16:03
Thanks for the update. I'll close this issue for now then.

**Closed by knolleary** 2019-04-02 16:03 UTC
