### ISSUE TITLE
When installing packages using palette manager the nodes of dependencies are not discovered

### ISSUE THREAD

**Issue by tve** [node-red/node-red#3529] opened 2022-04-13 01:20 UTC
### Current Behavior

Use the palette manager to install a package from the flow library that has dependencies that themselves have nodes. For example, node-red-fd-corewidgets has node-red-flexdash as dependency, which has node-red-flexdash-plugin as dependency. Both dependencies have nodes/plugins that need to be discovered for things to work correctly. As of NR v2.2.2 the dependencies are installed but not discovered/loaded. This is particularly painful when using docker because a restart of NR requires restarting the container.

### Expected Behavior

The expected behavior is that installing a package using the flow manager behaves the same way as if one had installed the package using NPM, just that it happens from within NR. But the reality is that this is not the case and leads to awful situations where config nodes in the dependencies are not loaded and then while nodes from the primary package seem to work they don't actually do due to the missing config nodes.

### Steps To Reproduce

- Start NR
- Use the palette manager to install @flexdash/node-red-fd-corewidgets
- Drag one of the imported nodes in the flexdash category into a flow (for example the datetime node)
- Configure the node and observe that the "Grid" config doesn't have the expected drop-down to select an appropriate config node
- Restart Node-RED, edit the datetime node again and observe the now-present config node drop-down

### Environment

- Node-RED version: v2.2.2
- Node.js version: 14
- npm version: 8.x
- Platform/OS: Linux
- Browser: any

**Comment by tve** [comment] 2022-04-13 01:22
Forum thread: https://discourse.nodered.org/t/installing-a-module-fails-to-install-dependencies/60059

**Comment by knolleary** [comment] 2022-04-13 06:51
Duplicate of https://github.com/node-red/node-red/issues/569

**Closed** 2022-04-13 14:39 UTC
Labels: needs-triage
