### ISSUE TITLE
Context Data does not autoupdate

### ISSUE THREAD

**Issue by aunwin** [node-red/node-red#2659] opened 2020-07-20 15:21 UTC
When selecting autoupdate for variables in the context menu section for flow, manually clicking the refresh button is still required.

### What are the steps to reproduce?

Install NodeRed on Ubuntu 18_04
Wire two Injection nodes (true, false) to a change node that sets a flow.variablename to msg.payload
Open Context Menu
Open Flow Section
Activate "Refresh on selection change"
Deploy Flow
Click true/false injection nodes and watch Flow section of the context menu. No change visible
Click Refresh -> flow.variablename change becomes visible

### What happens?
Autorefresh of Flow variables in contextmenu is not reflexted in the displayed value of context menu table

### What do you expect to happen?
 flow.variablename change becomes visible in context menu directly, without manually clicking the refresh button

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.6
- [ ] Node.js version: v8.10.0
- [ ] npm version: 3.5.2
- [ ] Platform/OS: Ubuntu 18_04
- [ ] Browser: Firefox 78.0.2 (64-Bit)

**Comment by knolleary** [comment] 2020-07-20 15:23
The option you have enabled is `Refresh on selection** change`.
The option is not 'Refresh whenever the value changes'. 

Have you changed selection in the editor?

**Comment by aunwin** [comment] 2020-07-20 15:37
Changing to Debug Output and then back to context menu does not work. if `Refresh on selection change` is only fullfilled when changing the tab of the current flow, I think it would be the default expectation to assume the context menu values are either updated or displayed as out of date. Why would that auto-refresh option not also autoupdate live without changing the tab? Am I missing a good reason or does this now turn into a feature request?

**Comment by knolleary** [comment] 2020-07-20 15:39
We specifically haven't done live views of the data due to the potential performance impact that would have.

**Comment by knolleary** [comment] 2020-07-30 22:01
Closing this issue because it is working as designed.

I appreciate having a mode that auto-refreshes would be helpful in some cases, but that is not a trivial change to make.

I have added an item to the backlog so it doesn't get forgotten about - we don't use the issue list for feature requests that are not in the immediate plan.

https://trello.com/c/lGjxwTFX

**Closed by knolleary** 2020-07-30 22:01 UTC
