### ISSUE TITLE
Possible bug re non-localfilesystem storage

### ISSUE THREAD

**Issue by colingoldberg** [node-red/node-red#634] opened 2015-05-01 15:30 UTC
I think I have found a bug - starting in server.js - regarding the 'storage' value when an alternative storage module is being used.

/red/storage/index.js itself seems to do the right thing in setting storageModule.  But it looks like server.js still relies on the initial value of 'storage' in function start() as in the following:

```
if (settings.httpAdminRoot !== false) {
    require("./api").init(app,storage);
}
```
I hope this is helpful.

Colin G

**Comment by knolleary** [comment] 2015-05-01 15:36
The `storage` variable in `server.js` is correctly a reference to `red/storage/index.js`. It acts as a wrapper to whatever storage module is actually loaded under the covers of the storage module.

Do you have an actual symptom that led you to raise this or is it by inspection of the code? Because we use the storage plugin mechanism extensively when running in the Bluemix cloud environment and it works.

**Comment by colingoldberg** [comment] 2015-05-01 15:43
It seemed that functions down the line from api - eg. strategies, tokens had the wrong value of 'storage' when I tried to log in/retrieve flows.

I tested a version that referenced storage.storageModule() (I added storageModule() temporarily) and this seemed to correct it.

Colin G

**Comment by knolleary** [comment] 2015-05-01 15:54
What I'm saying is there is only one value of storage - ie the result of `require("red/storage/index.js")`. It provides the interface that other parts of the code should call - which are then delegated to the underlying storage module.

I've just created a clone of the `localfilesystem` module, stuck in some debug against the various api calls, pointed at it with `storageModule` setting and I see the custom storage module being used correctly.

As I mentioned, we use this system extensively in a production system and don't see any issues. If you have a series of steps to reproduce what you are seeing, that would be helpful.

**Comment by knolleary** [comment] 2015-05-13 20:30
Hi @colingoldberg - do you have any updates on this? I've not been able to recreate any misbehaviour of the storage api.

**Comment by colingoldberg** [comment] 2015-05-14 21:23
Hi,

I've not pursued this, so I don't really have any more information for 
you. It is quite possible that I got confused, so I will understand if 
you close it.

Regards

Colin Goldberg

**Comment by knolleary** [comment] 2015-05-15 13:33
Thanks for the update Colin. I'm going to close this, but please do reopen if you find something we need to look at.

Nick

**Closed by knolleary** 2015-05-15 13:33 UTC
