### ISSUE TITLE
JSON convert  doesn't  throw any catch errors (anymore)

### ISSUE THREAD

**Issue by YEUAM** [node-red/node-red#2909] opened 2021-03-23 14:31 UTC
### What happens?

pass empty or corrupted  JSON payload ... no error , no out msg ..

### What do you expect to happen?

catch error "unexpected token"....

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.9   (docker)
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS: ubuntu 18.04
- [ ] Browser: chrome

```javascript 

70-JSON_spec.js 

161 :          } catch(err) { done(err) }

```` 
found this  https://discourse.nodered.org/t/node-error-not-caught-in-catch-node/1301/2

"So calling node.error() with one argument will not trigger a Catch node."

**Comment by knolleary** [comment] 2021-03-23 14:51
Can you provide an example flow that demonstrates the issue?

You've linked to code in the unit tests for the node - not the actual code for the node.

The relevant code is here:

https://github.com/node-red/node-red/blob/bccfd21cf46da7dfdde9653466f218fb3459ad7d/packages/node_modules/%40node-red/nodes/core/parsers/70-JSON.js#L56

Any error thrown here is caught and passed to `done()` which means it will be properly logged and be catchable with a catch node.

**Comment by YEUAM** [comment] 2021-03-23 15:50
Hello ,

thanx for your fast response

I prepared the demo flow ….  And it was working … throw’s  „unecpected ..“  errors

After that , the „original“  flow was also working again ….

I  swear  it wasn‘ t working bevor .. looked the whole day to find the problem …
[Ein Bild, das Text, drinnen enthält.  Automatisch generierte Beschreibung]



I’am not entirely sure .. but it starts  working  after I connect the Debug node directly to the catch node output ….

( next time I delete the  „not working“  node an re-insert them ..  )



[Ein Bild, das Text, drinnen, Karte enthält.  Automatisch generierte Beschreibung]








Debug of „original“  flow now like expected :

***@***.***D72004.38548460]



_______________________________________
Mit freundlichen Grüßen
Best regards
Lep pozdrav
Yoroshiku onegaishimasu / 敬具

i.A. Meier Andreas
Software engineering
PLC Department


YASKAWA Europe GmbH
Yaskawastr. 1*
85391 Allershausen
GERMANY
www.yaskawa.eu.com<http://www.yaskawa.eu.com/>

P +49 (0) 1511 749 7058
***@***.******@***.***>

*Warenanlieferung/Delivery of goods: Yaskawastr. 3, 85391 Allershausen
P Please consider the environment before printing this email

Von: knolleary ***@***.***>
Gesendet: Dienstag, 23. März 2021 15:52
An: node-red/node-red ***@***.***>
Cc: Andreas Meier ***@***.***>; Author ***@***.***>
Betreff: Re: [node-red/node-red] JSON convert doesn't throw any catch errors (anymore) (#2909)


Can you provide an example flow that demonstrates the issue?

You've linked to code in the unit tests for the node - not the actual code for the node.

The relevant code is here:

https://github.com/node-red/node-red/blob/bccfd21cf46da7dfdde9653466f218fb3459ad7d/packages/node_modules/%40node-red/nodes/core/parsers/70-JSON.js#L56<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-red%2Fnode-red%2Fblob%2Fbccfd21cf46da7dfdde9653466f218fb3459ad7d%2Fpackages%2Fnode_modules%2F%2540node-red%2Fnodes%2Fcore%2Fparsers%2F70-JSON.js%23L56&data=04%7C01%7CAndreas.Meier%40yaskawa.eu.com%7C6aaf1009f4ca4b36122208d8ee0b389b%7C7323b23de4294dc499b5726501252240%7C0%7C0%7C637521079279010670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gUjgMNHnOxtFd1Zeh352IHFIdhgZ%2BHVItxPr%2BFvcyek%3D&reserved=0>

Any error thrown here is caught and passed to done() which means it will be properly logged and be catchable with a catch node.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnode-red%2Fnode-red%2Fissues%2F2909%23issuecomment-804967595&data=04%7C01%7CAndreas.Meier%40yaskawa.eu.com%7C6aaf1009f4ca4b36122208d8ee0b389b%7C7323b23de4294dc499b5726501252240%7C0%7C0%7C637521079279010670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kt7MnndPensXATNkoTgJeRerdxpvdL0JUZM22F3URZo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANLW35IIQVH34C52QQOMDD3TFCTJFANCNFSM4ZVJSGVA&data=04%7C01%7CAndreas.Meier%40yaskawa.eu.com%7C6aaf1009f4ca4b36122208d8ee0b389b%7C7323b23de4294dc499b5726501252240%7C0%7C0%7C637521079279020625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5k%2F7O%2FiE6IRJVARRoQEp2p737ikShyA3owg7BoMaxfE%3D&reserved=0>.


------------------------------------------------------------------------------------------------------------------------------
Geschaeftsfuehrer/Managing Directors: Manfred Stern, Bruno J. Schnekenburger, Marcus Mead
Amtsgericht/Local Court: Frankfurt, Commercial register no. 88369
Headquarters: YASKAWA Europe GmbH, Hauptstr. 185, D-65760 Eschborn
------------------------------------------------------------------------------------------------------------------------------
CONFIDENTIALITY: This e-mail and any attachments are confidential and may also be privileged.
If you are not the named recipient, please notify the sender immediately and do not disclose the contents to another person,
use it for any purpose, or store or copy the information in any medium.

**Comment by knolleary** [comment] 2021-03-23 16:16
I think some of your reply has been lost as you've sent it via email. Can you reshare the images via the github UI directly?

I think you are saying you cannot reproduce this yourself now? If so, can we close this issue?

**Comment by YEUAM** [comment] 2021-03-23 21:11
yes , we can can :-)

**Closed** 2021-03-23 21:30 UTC
