### ISSUE TITLE
New grunt File Append test fails on Windows 10 PC

### ISSUE THREAD

**Issue by shrickus** [node-red/node-red#1352] opened 2017-07-24 15:37 UTC
After pulling the latest 0.17.5 code from github, and running grunt, the test is failing on Windows 10 with this error:
```
    file out Node
      √ should be loaded
      √ should write to a file (160ms)
      √ should append to a file and add newline (162ms)
      √ should append to a file after it has been deleted  (313ms)
      1) should append to a file after it has been recreated
      √ should use msg.filename if filename not set in node (158ms)
      √ should be able to delete the file (159ms)
      √ should warn if filename not set (156ms)
      √ ignore a missing payload (157ms)
      √ should fail to write to a ro file (161ms)
      √ should fail to append to a ro file (161ms)
      √ should cope with failing to delete a file (185ms)
      √ should fail to create a new directory if not asked to do so (append) (157ms)
      √ should try to create a new directory if asked to do so (append) (158ms)
      √ should fail to create a new directory if not asked to do so (overwrite) (157ms)
      √ should try to create a new directory if asked to do so (overwrite) (158ms)
    file in Node
      √ should be loaded
      √ should read in a file and output a buffer
      √ should read in a file and output a utf8 string
      √ should read in a file and output split lines with parts
      √ should read in a file and output a buffer with parts
      √ should warn if no filename set (157ms)
      √ should handle a file read error


  362 passing (51s)
  1 failing

  1) file Nodes file out Node should append to a file after it has been recreated :
     Error: EPERM: operation not permitted, open 'C:\NODE\node-red\test\resources\50-file-test-file.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Timeout._onTimeout (test\nodes\core\storage\50-file_spec.js:161:28)
```

My current PC configuration includes:
```
Welcome to Node-RED
===================

24 Jul 11:26:22 - [info] Node-RED version: v0.17.5-git
24 Jul 11:26:22 - [info] Node.js  version: v6.9.1
24 Jul 11:26:22 - [info] Windows_NT 10.0.14393 x64 LE
```

**Comment by Kazuki-Nakanishi** [comment] 2017-08-23 07:14
This issue comes from this commit. https://github.com/node-red/node-red/commit/2aced893c6933c2c7ef94dccbda3bba103fa4b68

On the Windows environment, the unlinked file won't be completely deleted until its file handle is closed.  The simple JavaScript code to check the phenomenon is as follows.
```
var fs = require("fs-extra");
var fileToTest='a.txt';

var wstream = fs.createWriteStream(fileToTest, { flags:'a', autoClose:true });
//wstream.end();  // if you uncomment this, it works well.
fs.unlinkSync(fileToTest);
console.log('unlink done.');
setTimeout(function(){}, 5000);
```

As the test case 'should append to a file after it has been recreated' in 50-file_spec.js deletes a file without calling node.wstream.end(), the following function "fs.writeFileSync" failed.

There are three options to fix this problem.

1. Remove the line 'fs.writeFileSync(fileToTest,"");' from 50-file_spec.js.
2. Skip this test case in 50-file_spec.js. on Windows environment.
3. Do not reuse the stream in 50-file.js.

I came up with a problem relating to option 3.
```
[{"id":"b4acf6ee.418328","type":"inject","z":"29e89e78.b7b142","name":"Click me first","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":130,"y":40,"wires":[["5aceaff3.bf3e6"]]},{"id":"5aceaff3.bf3e6","type":"file","z":"29e89e78.b7b142","name":"","filename":"a.txt","appendNewline":true,"createDir":false,"overwriteFile":"false","x":310,"y":40,"wires":[]},{"id":"22c4d7a7.26d838","type":"inject","z":"29e89e78.b7b142","name":"Click me next","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":130,"y":100,"wires":[["24148538.10294a"]]},{"id":"24148538.10294a","type":"file","z":"29e89e78.b7b142","name":"","filename":"a.txt","appendNewline":true,"createDir":false,"overwriteFile":"delete","x":330,"y":100,"wires":[]}]
```

When you run the first flow, "a.txt" will be created.  Then even if you run the second flow, the file will not be deleted on the Windows explorer.  The file will be deleted when node.wstream.end() was called (e.g. click deploy button).  But of course, choosing option 3 is a trade-off with performance.

@knolleary 

Could you please tell me which option is the best?

**Comment by shrickus** [comment] 2017-09-08 14:26
The latest version of code no longer fails with this error, but now another file-based test is failing:

```
  1) LocalFileSystem "before each" hook:
     Error: done() called multiple times
    at Suite.<anonymous> (test\red\runtime\storage\localfilesystem_spec.js:26:5)
    at Object.<anonymous> (test\red\runtime\storage\localfilesystem_spec.js:23:1)
    at Module.load (node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at require (internal/module.js:20:19)
    at Array.forEach (native)
    at Object.<anonymous> (node_modules\grunt-simple-mocha\tasks\simple-mocha.js:29:20)
    at Object.<anonymous> (node_modules\grunt\lib\grunt\task.js:255:15)
    at Object.thisTask.fn (node_modules\grunt\lib\grunt\task.js:73:16)
    at Object.<anonymous> (node_modules\grunt\lib\util\task.js:294:30)
    at Task.runTaskFn (node_modules\grunt\lib\util\task.js:244:24)
    at Task.<anonymous> (node_modules\grunt\lib\util\task.js:293:12)
    at node_modules\grunt\lib\util\task.js:220:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Looks like it may be a problem with the test itself?

**Comment by shrickus** [comment] 2017-09-29 14:01
It seems like Windows file handling will always have some quirks. Here is another failing test:

```
  369 passing (49s)
  1 failing

  1) file Nodes file out Node should append to a file after it has been recreated :
     Error: EPERM: operation not permitted, open 'C:\NODE\node-red\test\resources\50-file-test-file.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Timeout._onTimeout (test\nodes\core\storage\50-file_spec.js:161:28)

```

**Comment by Kazuki-Nakanishi** [comment] 2017-10-02 08:00
Thanks for your information.
Although I was struggling how to close the file handle, I noticed that calling `n1.close();` just after the `unlinkSync` solved this problem.
Would you like to raise a pull request or may I raise it on behalf of you?

With regard to the problem of `localfilesystem_spec.js`, I reproduced this problem by running the test case again and again (about 1,000 times).  But I have no idea to solve it so far.
Anyway, I think that a new issue should be opened as the problem seems different from this issue.

**Comment by shrickus** [comment] 2017-10-06 16:27
Yes, I've verified that adding the call to `n1.close();` does fix the test on my Windows OS. Thank you!
Please feel free to raise a pull request if you don't mind...

As for the other issue, I'm not seeing that as a problem any more.

**Comment by knolleary** [comment] 2020-10-09 17:02
Looks like this was fixed by the merged PR.

**Closed by knolleary** 2020-10-09 17:02 UTC
