### ISSUE TITLE
Too large msg causes the flow to stop

### ISSUE THREAD

**Issue by yeudit** [node-red/node-red#587] opened 2015-03-10 15:30 UTC
Hi,

my flow message contains a large object (parse result from a large xml object)
and it takes long time(around 10 mins) until the message is cloned,
so that the flow stopped for around 10 min.

I changed the clone method to something like that:
var m = JSON.parse(JSON.stringify(msg));
(https://github.com/node-red/node-red/blob/master/red/util.js#L48)

and everything works much faster.

is there something wrong with my fix?

Thanks

**Comment by knolleary** [comment] 2015-03-10 15:37
Hi,

that method will strip any message properties that cannot be represented as JSON - for example Function properties, and will modify Date properties to their string representation, but not restore them back to Date objects. 

Note that we try to minimise cloning - we only do so when we detect a message is being sent to more than one recipient. So it should be possible to design your flow that avoids cloning the large payload any more than is strictly necessary.

**Comment by yeudit** [comment] 2015-03-10 16:20
Thanks

BTW, I noticed that it took for me so long because of my PC, in another PC it finished after less than a minute.

**Comment by knolleary** [comment] 2015-03-18 22:56
As it isn't clear there is anything we're going to do for this issue, unless you think otherwise, I'm going to close it.

**Closed by knolleary** 2015-03-18 22:56 UTC

**Comment by mfeblowitz** [comment] 2015-04-17 19:12
I'd like to reopen this, as I've seen what I think is the same behaviour. I inject a large string (approx 800 characters) containing rdf. When I close the node dialog and press Deploy, the flows stop, for a very long time, and eventually restart. It seems like the time goes up exponentially, past roughly  700 characters.

I know this seems like a daft thing to do, and I don't expect to continue. But it might be an issue at times.

**Comment by knolleary** [comment] 2015-04-17 19:16
@mfeblowitz can you quantify what sort of pause you're seeing? And is it just on deploy or each time you inject the large message? (although I wouldn't consider 700 chrs to be large)

**Comment by mfeblowitz** [comment] 2015-04-17 19:30
For 1260 character string, placed in the payload field of the inject node, it took 2 minutes exactly between pressing Deploy and seeing the deployment success message (and seeing the blue dot disappear). That's long enough for most users (including me) to thing that it was fatal and/or there was something wrong with the system, etc. The resultant flow exported instantly and contains 2377 characters.

**Comment by knolleary** [comment] 2015-04-17 19:32
Odd - really wouldn't expect that sort of thing. What are you running on? Raspbery Pi/Bluemix/Laptop...

**Comment by mfeblowitz** [comment] 2015-04-17 19:34
Yeah - surprising. I was on a beefy linux host and tried it on my mbp and both were having issues with it. Using Firefox 31.6.0 ESR on both machines.

**Comment by knolleary** [comment] 2015-04-17 19:34
OK - will have a look.

**Comment by mfeblowitz** [comment] 2015-04-17 19:38
Interesting - I cut the size down to 790 characters on the Linux host and it took exactly 2 minutes there, too. Bigger machine, less text. Same exact think. Is the a timeout thing?

**Comment by dceejay** [comment] 2015-04-17 21:17
Hi Mark - I pushed a fix for the Stomp node to npm - (v0.0.4) - it wasn't closing the client properly which could easily cause the timeout you are seeing.

**Comment by mfeblowitz** [comment] 2015-04-17 22:36
You seem to be right about the timeout having to do with the Stomp node, but it seems that the fix didn't eliminate the issue. I'm using both the stomp-in and stomp-out nodes. Did the fix address both?

**Comment by dceejay** [comment] 2015-04-17 22:43
Yes - it was actually there on the in one - but no the out - now they should both be the same... but obviously not quite.... As you have the server to hit against... can you try messing with close functions (lines 92 and 145 of 18-stomp.js)

eg where we have
            if (node.client) {
                node.client.on("disconnect", function() { done(); });
                node.client.disconnect();
            }

try  (and see when DONE!!! get printed... - immediately ? after delay?)
            if (node.client) {
                node.client.on("disconnect", function() { console.log("DONE!!!"); done(); });
                node.client.disconnect();
            }
or (which should exit quickly - but isn't actually waiting for disconnect to finish so may cause other problems...)
            if (node.client) {
                node.client.disconnect();
                done();
            }
Thanks for helping.

**Comment by mfeblowitz** [comment] 2015-04-20 23:39
(We should probably create a stomp-node issue for this.)

I've tried a few things. I  noticed:
* all cases involve one or the other stomp node 
* in all such cases, "Stopping flows" appears once, then a 2-minute wait, and another "Stopping flows" immediately followed by a Starting flows " and "Started flows"
* just after the first "Stopping flows" message occurs, there is an indicator that the DISCONNECT message went out from the stomp node client(.js) to activemq, and an indicator from activemq that it was received.
* there are *no* messages from the stompout or stompin close callbacks. 
* removing the callbacks eliminates the wait, but I assume that just buries the problem.

As far as I can tell, the problem is deeper - possibly  in the stomp client or in the ActiveMQ stomp connector (not likely the latter). It does appear that the stomp client sends the DISCONNECT message - at least that code gets executed. And it appears that the DISCONNECT  messages are seen in activeMQ. My guess is that there's something wrong in the callback chain. I'll look at that later.

Mark

**Comment by knolleary** [comment] 2015-04-21 07:55
@mfeblowitz interesting - can you raise this over on the node-red-nodes issue tracker: https://github.com/node-red/node-red-nodes/issues

Thanks!

**Comment by mfeblowitz** [comment] 2015-04-21 15:44
Issue #112 <https://github.com/node-red/node-red-nodes/issues/112>.
