### ISSUE TITLE
node-red erro in function since upgrade to Version 3.0.2

### ISSUE THREAD

**Issue by github6043** [node-red/node-red#4005] opened 2023-01-04 12:19 UTC
### Current Behavior

FUNCTION check MAC, see below printscreen

I get an "error in Javascript code" since the upgrade to node-red Version 3.0.2.
The function code looks like 
```
const lastSeenSeconds = 15;
let presenceCutoff = (new Date() - (lastSeenSeconds * 1000)) / 1000;
const people = {
    "presence/s....": "d2:84:23:xxxxxxx",
    "presence/j.....": "16:97:2a:xxxxxxx"
};

return Object.keys(people).map(function (topic) {
    let devices = msg.payload.filter[0](device => device.name === people[topic] && device.last_seen > presenceCutoff);
    return {
        topic: topic,
        retain: true,
        payload: devices.length > 0
    };
});
```

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0.2
- Node.js version:
- npm version:
- Platform/OS: Ubuntu 20
- Browser:

**Comment by github6043** [comment] 2023-01-04 12:20
![image](https://user-images.githubusercontent.com/40850921/210553918-61312054-9b73-4ee1-907e-65f82a5ef95e.png)

**Comment by github6043** [comment] 2023-01-04 12:21
![image](https://user-images.githubusercontent.com/40850921/210554064-ae23f3bb-52d0-46a4-a790-270e80d1ec46.png)

**Comment by github6043** [comment] 2023-01-04 12:22
Client Devices is a Unifi Controller Version 7.3.76

**Comment by knolleary** [comment] 2023-01-04 12:24
Hi @github6043 

The quick fix is to change the second line of your code to:
```
let presenceCutoff = (new Date().getTime() - (lastSeenSeconds * 1000)) / 1000;
```

If you had opened up the Function node, the error would have been highlighted for you:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/51083/210554326-d2a54cb7-af89-4046-8365-768db058b436.png">

**Comment by github6043** [comment] 2023-01-04 13:38
I changed the line to

    let devices = **msg.payload[0].filter**(device => device.name === people[topic] && device.last_seen > presenceCutoff);

but still get

"TypeError: msg.payload[0].filter is not a function"

**Comment by knolleary** [comment] 2023-01-04 13:57
At this point, we're debugging your application rather than discussing a Node-RED bug. We prefer to do that on the [community forum](https://discourse.nodered.org) so the whole community can help, rather than depend on the core development team.

I believe your screenshot shows `msg.payload` is an array of objects. `msg.payload[0]` will be the first object in that array - and objects do not have a `filter` function.

Maybe you want to filter the list of devices in `msg.payload`? If so, you'd use `msg.payload.filter(....)`

**Comment by Steve-Mcl** [comment] 2023-01-04 14:42
Hi @github6043 as Nick points out, this is not a bug. Please head over to the forum or slack of you need help - the guys over there are super helpful.

I will close this as complete but please don't hesitate to head back here if you believe there is a bug.

Thanks.

**Closed by Steve-Mcl** 2023-01-04 14:42 UTC
Labels: question
