### ISSUE TITLE
Multiple various errors appearing when using groups

### ISSUE THREAD

**Issue by johnekarlsson** [node-red/node-red#2668] opened 2020-08-03 20:12 UTC
**Setup**
Home Assistant (prev. Hassio) running on raspberryPi
None Red running as add-on.
Multiple browsers and operating systems have been tested on client side.
Everything is updated to lastest available versions:
- Node-RED: 1.1.0
- Home assistant node red-addon: v.7.0.0

**Problem description**
- Suddenly, when developing in node red, the deploy button cannot be pressed. It is red, but nothing happens when I press it.
- Keyboard shortcut stops working (cmd-z brings back the last closed browser window, instead of functioning within node red).
- Some nodes are impossible to select. Nothing happens when I click on them.
- Some tabs cannot be deleted (they seem to be deleted but can still be found by searching)

This error code appears in the browser console when I press deploy:
`TypeError: undefined is not an object (evaluating 'e.id')`

These error codes appear when the page is loaded, but I’m not sure they are connected to this:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (purify.min.js.map, line 0)`
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (gridstack.min.map, line 0)`
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (gridstack.min.map, line 0)`

**Result of troubleshooting**
When I delete the flows.json-file and start node red, everything works again (but of course without my nodes). After much trouble shooting, I found that the problem was caused by the use of groups. When I remove all groups from the flow.json-file all problems are gone.

**Comment by hardillb** [comment] 2020-08-03 20:18
Just checking, you said everything is updated to the latest, but then list v1.1.0 of Node-RED when v1.1.2 is the latest release.

Also could you provide a flow file with groups that reproduces the problem?

**Comment by knolleary** [comment] 2020-08-03 20:22
There were some important fixes around groups in 1.1.1 and 1.1.2. The HA addon really really needs to be updated to stop users hitting known issues.

**Comment by johnekarlsson** [comment] 2020-08-04 07:09
Thanks for quick replies! I must admit I didn't realize that the HA version was not using the latest node-RED version. As a relatively heavy user of NR I should probably look into running this as a stand alone application parallel too HA, instead of as an add-on.

Should I close this bug, and we can assume/hope that my errors has been solved in 1.1.1/2?

**Comment by knolleary** [comment] 2020-08-04 08:12
As it stands, there are no known issues with groups in 1.1.2 - and it has been a few weeks since it was released. So I'm pretty certain you will be hitting known issues here.

I'll close this issue.

**Closed by knolleary** 2020-08-04 08:12 UTC
