### ISSUE TITLE
Fail Service Node Red

### ISSUE THREAD

**Issue by dedynobre** [node-red/node-red#1844] opened 2018-07-25 09:38 UTC
I have problem with service to node red.
With this messagem:

25 Jul 02:35:47 - [red] Uncaught Exception:
25 Jul 02:35:47 - Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
    at Socket.onListenError (dgram.js:362:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at _handle.lookup (dgram.js:267:14)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.

25 Jul 02:36:15 - [info] Node-RED version: v0.18.7
25 Jul 02:36:15 - [info] Node.js  version: v8.11.3
25 Jul 02:36:15 - [info] Linux 4.14.52+ arm LE

**Comment by knolleary** [comment] 2018-07-25 09:39
This will be caused by a contrib node that does not have appropriate error handling in place.

What nodes have you got in your flow that try to do things on the network?

**Comment by knolleary** [comment] 2018-07-25 09:40
This is already being discussed [here](https://discourse.nodered.org/t/node-red-connection-lost/1724/11). Raising an issue to split the conversation won't help get it resolved.

**Comment by knolleary** [comment] 2018-07-29 09:34
Closing this issue as it has been discussed on the forum.

**Closed by knolleary** 2018-07-29 09:34 UTC

**Comment by dedynobre** [comment] 2018-07-30 00:58
Ok.
