### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by kohichikoyama** [node-red/node-red#1661] opened 2018-03-06 05:53 UTC
### What are the steps to reproduce?
1,http input node configured for POST
2,http response
3,POST 1MB of data(JSON)
　　　・Content-Type: 'text/plain'　→OK
　　　・Content-Type: 'application/x-www-form-urlencoded'　→OK
　　　・Content-Type: 'application/json'　→NG

### What happens?
ERROR Message "PayloadTooLargeError: request entity too large"

### What do you expect to happen?
The bodyParser limit is not set

file: node-red/nodes/core/io/21-httpin.js
var bodyParser = require("body-parser");
var jsonParser = bodyParser.json();
var urlencParser = bodyParser.urlencoded({extended:true});

limit　(https://github.com/expressjs/body-parser)
Controls the maximum request body size. If this is a number, then the value specifies the number of bytes; if it is a string, the value is passed to the bytes library for parsing. Defaults to '100kb'.

I want a limit option
→　var jsonParser = bodyParser.json({limit: '5mb'});
→　var urlencParser = bodyParser.urlencoded({limit:'5mb',extended:true});

### Please tell us about your environment:

- [ ] Node-RED version:0.18.4
- [ ] node.js version:6.12.3
- [ ] npm version:3.10.10
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment] 2018-03-06 20:14
Duplicate of #1278

**Closed by knolleary** 2018-03-06 20:14 UTC
