### ISSUE TITLE
Function Node Editor Bg gone to White (again)

### ISSUE THREAD

**Issue by 3ative** [node-red/node-red#3779] opened 2022-07-17 17:21 UTC
### Current Behavior

After update 3.0 the Function Node Editor background is White (not dark)
![image](https://user-images.githubusercontent.com/51385971/179417327-dc3a39b4-ae34-4eb1-8b61-e1a59c3b09f7.png)

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0
- Node.js version: v16.15.0
- npm version:
- Platform/OS: Home Assistant OS 8.2
- Browser: Chrome 103.0.5060.114

**Comment by hardillb** [comment] 2022-07-17 17:23
Please fill our the **whole** template and include details of which theme you are using.

**Comment by Steve-Mcl** [comment] 2022-07-17 17:24
I'm pretty sure this is due to the theme you are using not been updated to set the Monaco theme. 

Have you checked to see if there is an update to your current theme? 

You can also manually set the Monaco theme in the settings.js file of you wish.

**Comment by 3ative** [comment] 2022-07-18 01:01
> Please fill our the **whole** template and include details of which theme you are using.

I've tried to add all the info I could find. My NR is an add-on in Home Assistant.
If you need anything else, please let me know what and where/how to find it. :)

**Comment by 3ative** [comment] 2022-07-18 01:06
@Steve-Mcl 
Thanks for the reply... I've looked around and did notice that info too - Something about themes being managed by another rep.
Sadly, the instructions for updating didn't point me to anything I could use/understand - I'm not a Unix guy and my NR is an add-on in Home Assistant. 
I tried some of the commands I found, in what I think was Terminal, but got some errors about destination paths, etc.

**Comment by Steve-Mcl** [comment] 2022-07-18 07:31
Hi, we don't use HA so not certain we can help other than offer some pointers. You may need to ask for help on the HA forum.

1. I know that the excellent theme pack by @bonanitech has been updated for v3 & pretty sure the themes set an appropriate code editor theme
2. If you know how to (or can find out how to) edit your settings.js file , you can choose from any of the built in Monaco themes - take a look at this post on the forum: https://discourse.nodered.org/t/editor-text-size/53944/4

**Comment by Steve-Mcl** [comment] 2022-07-18 07:33
Also, I forgot the add, if this theme is provided/created by the HA team, It would probably be a good thing to let them know (via an issue on their repository) that the theme in question does not set an appropriate Monaco theme.

**Comment by bonanitech** [comment] 2022-07-18 09:56
@3ative, it looks like you have `theme: "vs"` enabled in your `settings.js`.
Just comment out that line and then restart Node-RED.

**Comment by 3ative** [comment] 2022-07-18 11:58
Thanks for all the replies ppl.

Like I said I'm in no way a linux guy 😁 but here's what I could find:
In the config tab of Node-Red (HA Add-on Page) I have set the theme;
![Screenshot 2022-07-18 12 42 57](https://user-images.githubusercontent.com/51385971/179504943-1b04b519-9558-4f5e-b517-9ef8857b7166.png)

And everything in the NR interface is the same colours as before, etc apart from the BG of the Function Node Editor- as seen in the OP.
- So [most] of the theme is being used. 

As for the settings.js, there is no [theme:] so, I'm guessing the above setting is covering that bit. :) 
```
    // The following property can be used to order the categories in the editor
    // palette. If a node's category is not in the list, the category will get
    // added to the end of the palette.
    // If not set, the following default order is used:
    paletteCategories: [
        'home_assistant',
        'subflows',
        'input',
        'output',
        'function',
        'social',
        'mobile',
        'storage',
        'analysis',
        'advanced'
    ],

    // Configure the logging output
    logging: {
        // Only console logging is currently supported
        console: {
            // Whether or not to include metric events in the log output
            metrics: false,
            // Whether or not to include audit events in the log output
            audit: false
        }
    },

    // Customising the editor
    editorTheme: {
        projects: {
            // To enable the Projects feature, set this value to true
            enabled: false
        }
    }
}
```
From what I can gather, this "midnight-red" theme IS still being used, it's just the Function Node Editor BG part of the theme itself that hasn't been updated.

- Also, while looking at the docs and other web page about updating themes... it talks about npm install to place a theme in a "theme" folder... which there isn't one in /config/node-red.

**Comment by bonanitech** [comment] 2022-07-18 17:21
I'll work with the add-on developer to find a fix for this.

**Closed** 2022-07-20 09:43 UTC
Labels: upstream

**Comment by knolleary** [comment] 2022-07-20 12:52
@3ative the core node-red project doesn't maintain *any* custom themes for the editor. They are mostly all provided by the excellent work done by @bonanitech.

The problem you are having will not lead to any code changes or fixes in Node-RED itself (which is what this issue list is for tracking) - this is what 'upstream' means in this context.

**Comment by 3ative** [comment] 2022-07-20 20:45
> @3ative the core node-red project doesn't maintain _any_ custom themes for the editor. They are mostly all provided by the excellent work done by @bonanitech.
> 
> The problem you are having will not lead to any code changes or fixes in Node-RED itself (which is what this issue list is for tracking) - this is what 'upstream' means in this context.

I understand now it's not a NR issue and is something in addition to... Thanks for the clarification too. 👍

**Comment by bonanitech** [comment] 2022-07-21 11:53
It looks like the problem is that they don't have `codeEditor` in their settings.

**Comment by bonanitech** [comment] 2022-07-21 12:15
@knolleary, shouldn't it work anyway?

**Comment by knolleary** [comment] 2022-07-21 12:54
@bonanitech can you explain a bit more? Is this not related to the theme then? Do you have a way to recreate this?

**Comment by bonanitech** [comment] 2022-07-21 13:07
If there is no `codeEditor` object in settings.js, it will not load the customizations made in the theme.

**Comment by Steve-Mcl** [comment] 2022-07-21 13:11
I'll take a look 

@knolleary is there time before 3.0.1 for me to see if I can resolve this?

**Comment by knolleary** [comment] 2022-07-21 13:23
@Steve-Mcl we need to get 3.0.1 released today. I would rather not being doing that late in the evening. If there's a fix that is forthcoming, then yes. Otherwise it'll have to wait until 3.0.2.

**Comment by Steve-Mcl** [comment] 2022-07-21 13:32
5 mins I will push modification - i believe is straight forward and non invasive. 

If it makes the cut, great. If not, then 3.0.2

**Comment by Steve-Mcl** [comment] 2022-07-21 13:47
@knolleary  PR done (tests running)

**Comment by bonanitech** [comment] 2022-07-21 14:43
Thanks, guys!

**Comment by 3ative** [comment] 2022-07-21 20:28
🥰 Great work guys... but,Alas it didn't make 3.0.1

![image](https://user-images.githubusercontent.com/51385971/180309079-4f5556cb-f60d-423b-a70a-59d7a3976e57.png)

Looking forward to 3.0.2 😀

**Comment by knolleary** [comment] 2022-07-21 20:29
@3ative 3.0.1 has not been published yet. Other things got in the way. We'll get it released tomorrow.

**Comment by 3ative** [comment] 2022-07-21 20:41
> @3ative 3.0.1 has not been published yet. Other things got in the way. We'll get it released tomorrow.

LOL Yeah, I saw this in my Home Assistant and got excited. 🤣

![Screenshot 2022-07-21 21 39 32](https://user-images.githubusercontent.com/51385971/180311253-cf031e44-dc96-4178-acd8-6825e3047ebc.png)

**Comment by 3ative** [comment] 2022-07-27 06:22
I can confirm that with the latest Home Assistant Add-on update for NR... Now is all good. 

Thanks go to everyone involved. 💖
