### ISSUE TITLE
[Node-RED 3.0.1] Cannot import subflow with junction node

### ISSUE THREAD

**Issue by tve** [node-red/node-red#3814] opened 2022-08-01 04:30 UTC
### Current Behavior

If I import a subflow with a junction node I get an error
`TypeError: Cannot read properties of undefined (reading 'z')`

### Expected Behavior

I expect the import to work correctly...

### Steps To Reproduce

- Create a subflow with one input and one output.
- Add a junction node.
- Wire the input to the junction, and the junction to the output.
- Create a flow.
- Add an inject node.
- Add a debug node.
- Add an instance of the subflow.
- Wire the inject to the subflow, then to the debug.
- Deploy.
- Select the three nodes in the flow and export to JSON (clipboard)
- Delete everything.
- Import from clipboard and paste the above export.
- Notice error pop-up and failure of the import. See error in browser console.

### Example flow

```
[
    {
        "id": "2c3373cd1260e484",
        "type": "subflow",
        "name": "Subflow 1",
        "info": "",
        "in": [
            {
                "x": 140,
                "y": 120,
                "wires": [
                    {
                        "id": "8a7a361c9ce014ef"
                    }
                ]
            }
        ],
        "out": [
            {
                "x": 540,
                "y": 160,
                "wires": [
                    {
                        "id": "8a7a361c9ce014ef",
                        "port": 0
                    }
                ]
            }
        ]
    },
    {
        "id": "bc913a4b5737cd8a",
        "type": "inject",
        "z": "029237ddce809f0d",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 210,
        "y": 120,
        "wires": [
            [
                "b73fb986f76958c1"
            ]
        ]
    },
    {
        "id": "f38c9423aa421828",
        "type": "debug",
        "z": "029237ddce809f0d",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 600,
        "y": 120,
        "wires": []
    },
    {
        "id": "b73fb986f76958c1",
        "type": "subflow:2c3373cd1260e484",
        "z": "029237ddce809f0d",
        "name": "",
        "x": 400,
        "y": 160,
        "wires": [
            [
                "f38c9423aa421828"
            ]
        ]
    }
]
```

### Environment

1 Aug 04:20:59 - [info] Node-RED version: v3.0.1
1 Aug 04:20:59 - [info] Node.js  version: v16.16.0
1 Aug 04:20:59 - [info] Linux 5.13.0-52-generic x64 LE

**Comment by knolleary** [comment] 2022-08-01 07:06
Duplicate of #3805

**Closed by knolleary** 2022-08-01 07:06 UTC
Labels: needs-triage
