### ISSUE TITLE
Truncated tweets and not receiving DMs - twitter node

### ISSUE THREAD

**Issue by Freyja-Folkvangr** [node-red/node-red#1840] opened 2018-07-23 21:07 UTC
### What happens?
Regarding the changes in the Twitter API, If the tweet is longer than 160 characters the twitter input node returns a truncated msg.tweet.text and msg.tweet.truncated is true.
Just a few tweets includes an extended_tweet object with the full text and entities.
Could you update the node and include the extended param to get the full tweet by default?
https://stackoverflow.com/questions/38717816/twitter-api-text-field-value-is-truncated

In the other hand, the twitter node is not receiving any incoming direct message. The Twitter app has the proper permissions.

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.7
- [] twitter node version: 1.0.1
- [ ] Platform/OS: Bluemix
- [ ] Browser: safari

**Comment by knolleary** [comment] 2018-07-23 22:02
Duplicate of https://github.com/node-red/node-red-nodes/issues/464 and https://github.com/node-red/node-red-nodes/issues/443

**Closed by knolleary** 2018-07-23 22:02 UTC
