### ISSUE TITLE
Latest Docker tag points to old version

### ISSUE THREAD

**Issue by corasaniti** [node-red/node-red#4852] opened 2024-08-13 07:00 UTC
### Current Behavior

Latest Docker tag points to old version

Yesterday I downloaded the latest Docker tag which pointed to nodered version:4.02.
![Immagine 2024-08-13 084859](https://github.com/user-attachments/assets/14f245dc-c887-47c4-9a4c-9f64a68d43bb)

This morning I get a notification that a new image is available :latest, but to my surprise when I pull the latest tag from the docker registry I get a nodered version of 3.11

The latest tag was tagged by mistake to a very old nodered version

![Immagine 2024-08-13 084739](https://github.com/user-attachments/assets/b9599207-03f6-4d55-93c8-459b89f1263c)

### Expected Behavior

Pulling last version with latest docker tag

### Steps To Reproduce

pull latest tag with command
docker pull nodered/node-red:latest

### Example flow

No flow

### Environment

- Node-RED version:
- Node.js version:4.02
- npm version:
- Platform/OS: amd64 and arm64
- Browser: chrome

**Comment by hardillb** [comment] 2024-08-13 07:33
Thanks, I know what the problem is. The 4.0.2 builds are re spinning at the moment which will fix it.

**Comment by hardillb** [comment] 2024-08-13 08:30
@corasaniti should be fixed now, and the build script for the 3.1.x containers has been updated to stop it happening again.

**Closed by hardillb** 2024-08-13 08:30 UTC
Labels: needs-triage

**Comment by corasaniti** [comment] 2024-08-13 08:36
> @corasaniti should be fixed now, and the build script for the 3.1.x containers has been updated to stop it happening again.

Thank you

**Comment by corasaniti** [comment] 2024-08-13 08:37
@hardillb 
Thank you
