### ISSUE TITLE
Node-Red freezes since 1.1.0

### ISSUE THREAD

**Issue by Hypnos3** [node-red/node-red#2697] opened 2020-09-10 19:13 UTC
With starting the Groups function Node-red freezes sometimes when clicking on a node in a Group and moving them.

There is nothing in the console:
![image](https://user-images.githubusercontent.com/12692680/92786795-d9104980-f3a8-11ea-8d4b-f8e67c634c3e.png)

When trying to reload the page after a while a popup from chrome says trhat a script trys very long time with the posibility to stop this.

Bug was also reported by other users:
https://discourse.nodered.org/t/node-red-1-1-2-released/29872/16
https://discourse.nodered.org/t/node-red-1-1-2-released/29872/18

### What are the steps to reproduce?

 - clicking a node inside a group multiple times. (Multiple clicks are necessary, because first click does only select the group and not the node inside them. It must be clicked often more then 2 times to select only the node inside the group)
 - moving the node
 - repeat this with another node inside the group
 - then on 3 times out of ten the node-red freezes, only completely reload of the page are possible

### What happens?

 - node red freezes, does not react on any other clock, mouse over, etc...

### What do you expect to happen?

normal working with node red and not ned to reload page and loose al changes what I have made.

### Please tell us about your environment:

- [ ] Node-RED version: Problems occures with Node-Red 1.1.2 and 1.1.3
- [ ] Node.js version: 14.7.0
- [ ] npm version: 6.14.7
- [ ] Platform/OS: Buildroot Linux
- [ ] Browser: Google Chrome 85.0.4183.83

**Comment by knolleary** [comment] 2020-09-10 19:14
Possibly a duplicate of #2686 - which has been fixed for the next release.

**Comment by Hypnos3** [comment] 2020-09-10 19:20
Yes, seems to be a duplicate. In the last case where it occurred, I also noticed that one of the flow's nodes is not part of the group.

Unfortunately this is not very noticeable and you only notice it when moving the group.

**Closed** 2020-10-19 11:58 UTC
Labels: duplicate
