### ISSUE TITLE
Using Google Chrome or Internet Explorer, the Node-RED menu does not always close

### ISSUE THREAD

**Issue by DSiekmeier** [node-red/node-red#1986] opened 2018-11-29 15:49 UTC
# What are the steps to reproduce?

- start Node-RED and open its menu
- Click on different places inside the browser window

# What happens?

- Clicking on a empty place of the flow keeps the menu open
- Clicking on a node or in the palette closes the menu

# What do you expect to happen?

- The behavior should be the same everywhere (IMO menu should be closed)

# Please tell us about your environment:

- Node-RED version: 0.19.5 and 0.18.7
- node.js version: 8.12.0
- npm version: 3.8.5
- Platform/OS: (X)Ubuntu 16.04
- Browser: Google Chrome 70.0.3538.110 (64 Bit) and Internet Explorer 11.0.9600

When using Firefox 63.0.3 the menu closes when clicking on empty space in flow.

**Comment by knolleary** [comment] 2020-10-09 17:22
I can't reproduce any cases of the menu staying open when the mouse clicks elsewhere. Going to close this issue.

If you can still recreate it on latest, then please do reopen with details.

**Closed by knolleary** 2020-10-09 17:22 UTC
